### PR TITLE
Introducing a tiled RCD demosaicer

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
The rcd demosaicer developed by Luis Sanz Rodríguez is publically available at
https://github.com/LuisSR/RCD-Demosaicing and is licenced under the GNU GPL version 3.

I came across this via the rt issue tracker Beep6581/RawTherapee#5908 and
have personally been using it in dt for some months.

The results are very good, quality is at least en-par with Amaze, maybe depending
on image content the results are slightly better or slightly worse, in my opinion better in most cases.

The biggest pro argument is less colour overshoot, the penalty maybe is marginally increased blur.
Having a demosaicer output with less overshoot makes this a better option for further processing.

I started developing the demosaicer by taking the algo from original github and adopted it to dt style.
Over time i learned how @heckflosse had improved the code by tiling, less omp overhead
and by adding sse2 code in the most time-critical internal loop as the compiler does not
vectorize here as good.

Further on we discussed many details and worked on performance on different machines.
Thanks a lot! Now it is really good, on darktable rcd is ~3x faster than amaze
and 30% faster than the non-cl ppg code. On my machine (pretty similar to the well known
9900k) i am now at ~135ms for a 45Mpix image. This is ~3 times as good as the non-tiled
version.

The border interpolation used the dcraw algorithm in the original code, there are minor issues so i chose the code used by rt as it has less artefacts. A border of 9 is always safe if tiling is used.

Unfortunately there is no paper describing the algorithm, we only have the README in the original git repo at
https://github.com/LuisSR/RCD-Demosaicing/blob/master/README.md

Also there is no formal quality analysis, at rawtherapee we have
https://rawpedia.rawtherapee.com/Demosaicing

But -- we have a lot of experience people made when using this demosaicer in rt.

Some notes for people testing the code

1) in demosaic.c you find the bitmask
     #define DEMOSAIC_TIMING 0
   - 01 --> add timing info for the demosaicers while tuning avoiding the mass of -d perf info
   - 02 --> prohibit fall back to ppg

2) You might want to tune the tiling size in rcd_demosaic.c, unfortunately this has to be
   selected at compile-time. Making this runtime specified reduces performance by ~50%

See former attempt #6738

### CODE REVIEW

**Comment by heckflosse** [comment]
> Further on we discussed many details and worked on performance on different machines.
Thanks a lot!

That was a really nice collaboration :+1: 

RCD is my preferred demosaicer in RawTherapee (mainly because it works best with sharpening). It's also faster than most of the other demosaicers.

Another advantage (related to dt) is, that the code is quite simple and it should be possible to code an GPU version much easier than for Amaze ;-)

**Comment by johnny-bit** [comment]
rcd_demosaic seems to have no includes, build is failing on missing intris methods so prolly needs moar includes.

**Comment by jenshannoschwalm** [comment]
Yeah, it seems that `#include <smmintrin.h>` is missing for one inlined function ...

**Comment by heckflosse** [comment]
I would 
```
#include <x86intrin.h>
```

**Comment by heckflosse** [comment]
> But -- we have a lot of experience people made when using this demosaicer in rt.

Just want to mention, that rcd since a while also is the default demosaice in [Siril](https://discuss.pixls.us/c/software/siril/34)

File: src/iop/rcd_demosaic.c [hunk 1]
```diff
@@ -0,0 +1,645 @@
...
+#define epssq 1e-10
+
+/* Some macros and inline functions taken from amaze_demosaic_RT */
+typedef __m128i vmask;
+typedef __m128 vfloat;
+
+#define F2V(a) _mm_set1_ps((a))
+#define LVFU(x) _mm_loadu_ps(&x)
+#define STVFU(x,y) _mm_storeu_ps(&x,y)
+#ifdef __SSE4_1__
```
Comment (TurboGit) [inline src/iop/rcd_demosaic.c:85]: So we require SSE to be available (either SSE4 or SSE2) which is optional in current dt code. Are we sure we have SSE available in all the target dt runs on ?

Comment (jenshannoschwalm) [reply src/iop/rcd_demosaic.c:85]: ok. i will add #if clause to enable the vector functions only in case we have see but there is only one internal loop that optionally takes sse code for speed.

Comment (johnny-bit) [reply src/iop/rcd_demosaic.c:85]: @TurboGit - dt can run on PowerPC which doesn't have sse (has altivec instead)... And it is possible that Apple M1 doesn't have sse and if by chance we'll have a way to support it then that's another platform without sse ;)

Comment (TurboGit) [reply src/iop/rcd_demosaic.c:85]: Ok, maybe that's a good ground for playing with the clone targets ? This will enable the best hardware support and possible gain some more speed.

Comment (johnny-bit) [reply src/iop/rcd_demosaic.c:85]: Clone targets is gcc only, LLVM should have it but the feature is in limbo (or so I gather from discussion with @LebedevRI )

Comment (LebedevRI) [reply src/iop/rcd_demosaic.c:85]: Please, please don't add any new SSE-only code. (ideally, don't manually vectorize at all)
x86 will die one day, but it will sunset way before that, way before people currently expect.

Comment (heckflosse) [reply src/iop/rcd_demosaic.c:85]: As @jenshannoschwalm wrote: The sse-code is optional. It just needs some more '#ifdef'

Comment (jenshannoschwalm) [reply src/iop/rcd_demosaic.c:85]: Some more comments for all of us to decide on a more profound base.

The code is definitely **not** SSE-only.

It has been performance-tuned for sse enabled machines.

Unfortunately the above sse-tuned code (A) is not only about specific sse vector functions but also about the way we access the lp filter in rcd which affects how good the compiler can vectorize.

There is also a tested generic optimized version (B) fully trusting the compiler.

Measuring the performance shows for the whole rcd-demosaicing process
1. On SSE- enabled machines the sse optimized version (A) is ~6-8% faster than (B)
2. On non-SSE machines version (A) is probably ~25% slower than (B)

So there is a trade-off somehow, whether we should have the probably fastest code on current mainstream CPUs or something more generic. I prefer it the way i proposed in the pr but this not a very stron opinion. Let me know.

Comment (heckflosse) [reply src/iop/rcd_demosaic.c:85]: @jenshannoschwalm 
> So there is a trade-off somehow, whether we should have the probably fastest code on current mainstream CPUs or something more generic.

There might be a possibility without a tradeoff: Use the >>1 indexing for the sse code and the normal indexing for non-SSE code. Just a thought...

**Comment by jenshannoschwalm** [comment]
Ok there have been two commits tackling:

1. The whole rcd code is not SSE only, it includes one sse-optimized code section for best performance on sse2-4 machines.
2. Macros and inline function only valid for sse specific stuff have been #ifdef -ed.
3. The loops in that section have been optimized to make non-sse code much more performant.
4. Some border stuff has been fixed.

I would prefer this to get merged including the sse specific code atm, (further working on performance in collaboration with @heckflosse to get rcd as fast as possible might follow in other pr's)

Please review & test

**Comment by jenshannoschwalm** [comment]
Forgot to mention, this fixes the tradeoff for non-sse machines mentioned before.

File: src/iop/rcd_demosaic.c (hunk 1 above)
Comment (erichkeane) [reply src/iop/rcd_demosaic.c:84]: > Ok, maybe that's a good ground for playing with the clone targets ? This will enable the best hardware support and possible gain some more speed.

See my response on #7075, that clarifies the state of Clang/GCC/ICC multiversioning a bit.

Comment (heckflosse) [reply src/iop/rcd_demosaic.c:84]: Would be a multiversioning for one out of 8 loops worth the effort to multiversion the whole algorithm? In my opinion SSE code for this one loop is much better to maintain...
The other loops are optimized pretty well by gcc, not as well by clang though...

Comment (heckflosse) [reply src/iop/rcd_demosaic.c:84]: >This will enable the best hardware support and possible gain some more speed.

Fot the users which need best hardware (CPU) support nothing will beat a `-march=native` build.

Comment (erichkeane) [reply src/iop/rcd_demosaic.c:84]: I don't really have the answer to that, typically we suggest that you benchmark to figure out when it is useful. That said, the multi-version function has a slight load-time performance hit (the 'resolution' of which version to use is handled when the library is loaded), and a slight call-time performance hit (since it is an indirect function call via a function pointer).

Depending on the performance gain possible for each version (particularly with SSE loops), this overhead is often more than acceptable.

Comment (jenshannoschwalm) [reply src/iop/rcd_demosaic.c:84]: Just some more notes about new performance checks on my system E-2288G

1. gcc -march=native could not get an extra gain
2. so using  __DT_CLONE_TARGETS__ also didn't help
3. i checked using clang and the performance was worse, there were other dt pr's reporting this

**Comment by johnny-bit** [comment]
When testing this demosaicer I used https://discuss.pixls.us/t/moire-nightmare-challenge-from-hell/21787 and it produces interesting results, seems "definitelly better" than PPG and is nice overall, however there can be some mazing artifacts (even amaze can produce funny mazing though), but i guess moire nightmare isn't good testing image for RCD ;)

**Comment by jenshannoschwalm** [comment]
One more commit from collaboration with Ingo, again a slight performance gain (~3%) resulting from lower cache mem pressure.

@TurboGit Anything i can do ...

**Comment by jenshannoschwalm** [comment]
The CI test is annoying atm, nothing related to latest commit anyway and it went ok a few days before

**Comment by johnny-bit** [comment]
Yeah, Ci is ATM annoying on windows and mac, just keep an eye on Linux
builds, that's the important stuff ;)

Btw I like this demosaicer 😃

pon., 21 gru 2020, 07:29 użytkownik Hanno Schwalm <notifications@github.com>
napisał:

**Comment by heckflosse** [comment]
@johnny-bit The mazing artifacts are also visible for the raw file you mentioned when using (in RT) no demosaic or monochrome
Here's s screenshot without demosaic which shows the patterns
grafik

**Comment by jenshannoschwalm** [comment]
Exactly that's the reason we have the `photosite` demosaicer in dt :-)

**Comment by heckflosse** [comment]
Though I (being a RawTherapee dev) do not use darktable, I would appreciate to get this pr merged. rcd is a good and fast demosaicer. Hanno and I spend a lot of time to optimize it to its current speed. The new optimizations will also go into the rt version of rcd and the librtprocess version, means also Filmulator, Siril and Rawproc (don't know if rawproc uses rcd) will benefit from the optimizations.

**Comment by johnny-bit** [comment]
I think rebase would be better behaved than merge... anyway - I really think this demosaicer is interesting and would be great to have it in darktable:) :+1:

**Comment by jenshannoschwalm** [comment]
> I think rebase would be better behaved than merge ...

Right, i just saw the github web interface offering and took that :-) Hadn't noticed that before and was just interested.

Yes, i also think this demosaicer is very good and pretty fast right now. Here i am working on dual demosaicing stuff already, is even more complicated to get it performant. Also finding out how dt's existing functions can be used best... More on this after (hopefully) this gets merged.

**Comment by johnny-bit** [comment]
> Here i am working on dual demosaicing stuff already

YAAASSS!!!

> More on this after (hopefully) this gets merged.

OMG YAAAASSSS!!!

**Comment by AxelG-DE** [comment]
I was one of the first, editing above PlayRaw and it was a hard one. If in future we could have a even better demosaicing, I'd be very happy :-)

**Comment by TurboGit** [comment]
I see some hints that this should be merged sooner than later :) Fine by me, just a note that at the moment I try to follow all the perfs changes and making sure those will be ok for 3.4.1 and so queued all them in the `next` branch. For this PR I need some time to review and so I always put at tomorrow the work. No worries I have this in my radar.

**Comment by phrrk** [comment]
Tried to build this PR under windows and get the following fatal compile error

```
In file included from C:/msys64/home/jim/github/darktable/src/iop/demosaic.c:48,
                 from C:/msys64/home/jim/github/darktable/build/lib/darktable/plugins/introspection_demosaic.c:55:
C:/msys64/home/jim/github/darktable/src/iop/rcd_demosaic.c: In function 'rcd_demosaic':
C:/msys64/home/jim/github/darktable/src/iop/rcd_demosaic.c:322:55: error: initialization of 'float (* const)[19600]' from incompatible pointer type 'float *' [-Werror=incompatible-pointer-types]
  322 |     float (*const rgb)[RCD_TILESIZE * RCD_TILESIZE] = dt_alloc_align_float((size_t)3 * RCD_TILESIZE * RCD_TILESIZE);
      |                                                       ^~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

File: src/iop/rcd_demosaic.c [hunk 2]
```diff
@@ -0,0 +1,621 @@
...
+        // STEP 3: Populate the green channel
+        // Step 3.1: Populate the green channel at blue and red CFA positions
+        for(int row = 4; row < tileRows - 4; row++)
+        {
+          int col = 4 + (FCRCD(row, 0) & 1);
+          int indx = row * RCD_TILESIZE + col;
+          int lp_indx = indx / 2;
+          // There has been quite some performance testing for the generic vs. SSE2 optimized loop, as the generated generic code (-O3)
+          // is not as fast as Ingos optmized code (~4% loss) we keep the SSE2 specific path.
+#ifdef __SSE2__
```
Comment (TurboGit) [inline src/iop/rcd_demosaic.c:428]: can you explain why there is a #ifdef there so some code with having SSE2 and no else part ? That is, there is something done only when SSE2 is supported ? Looks suspicious to me... At least, this certainly deserve a comment.

**Review by TurboGit — CHANGES_REQUESTED** [review]
Do not compile with gcc 10.2.1 and question about SSE.

File: src/iop/rcd_demosaic.c (hunk 2 above)
Comment (heckflosse) [reply src/iop/rcd_demosaic.c:428]: Because the loop counter is initialized before the loop and not inside the loop header, the code after the `#endif` handles the remaining pixels of the SSE code (if there are any) as well as the non SSE code. That's a pattern which reduces code duplication and in RawTherapee we get this question at least once per year ;-)

Comment (TurboGit) [reply src/iop/rcd_demosaic.c:424]: So as I said, we need a comment :)

Comment (jenshannoschwalm) [reply src/iop/rcd_demosaic.c:424]: I couldn't have this explained better, was just committing the compiler issue :-)

**Comment by jenshannoschwalm** [comment]
> Do not compile with gcc 10.2.1 and question about SSE.

I think it's done @TurboGit

**Comment by TurboGit** [comment]
Ok, works for me. Thanks.

**Comment by TurboGit** [comment]
Ok, I should have run the integration test before merging, this PR introduce a huge amount of error for example:

```
Test 0043-dithering-fs
      Image mire1.cr2
      CPU & GPU version differ by 1.17492e+06 pixels
      Max  dE         118.0244
      Mean dE         33.5388
      Count above max 793815
  FAILS: image visually changed
         see diff.png for visual difference
         (793815 pixels changed)
```

And indeed, the diff shows very strange patterns:

diff

@jenshannoschwalm : Can you have a look at this ? If you are not in a position to fix soon let me know and I can revert to ease my integration of others PR. TIA.

**Comment by jenshannoschwalm** [comment]
I will take care of this tonight and will report / fix.

**Comment by TurboGit** [comment]
Thanks !

**Comment by heckflosse** [comment]
replace
```
#ifdef __GNUC__
  #pragma GCC optimize ("-Ofast")
#endif
```
with
```
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC optimize ("-Ofast")
#endif
```
and at the end of rcd_demosaic.c add
```
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif
```

**Comment by johnny-bit** [comment]
Yeah, that might have something to do with it - we do know that optimizations do impact results of calculations and can (and do) break integration tests.

**Comment by heckflosse** [comment]
maybe better to use
```
#pragma GCC push_options
```
and 
```
#pragma GCC pop_options
```

**Comment by jenshannoschwalm** [comment]
It's indeed the problem, i oversaw fixing this in this pr too ...

**Comment by AxelG-DE** [comment]
Gentlemen,

just now I tried RCD on that pic:
https://discuss.pixls.us/t/moire-nightmare-challenge-from-hell/21787

and my finding is, the results are worse than amaze. Would you be interested in a screencast?

**Comment by jenshannoschwalm** [comment]
Yeah. But that image is a nightmare - as the title says :-) I don't think it is good for some proper testing

**Comment by johnny-bit** [comment]
@AxelG-DE - That image is nightmare and already has mazing artifacts with no demosaic ;) so results will always be weird on it ;)

test on something normal, not nightmarish ;)

**Comment by AxelG-DE** [comment]
:-)

Then I wonder, how C1 got that nice results. Separately from demosaic?

**Comment by johnny-bit** [comment]
C1 demosaic algos are proprietary. Same as any other proprietary raw processor. I think similarly to double-demosaic stuff from RT one could devise a double or even triple demosaicer to deal specifically with moire patterns, false colours, mazing artifacts etc. But hey - Let's be happy that @jenshannoschwalm introduced RCD to darktable! It's good for some things, same as VNG4 is good for some things and aMaZe is good for some things and PPG is probably not the worst choice for some things ;)

**Comment by jenshannoschwalm** [comment]
The mentioned example **is** a moire adventure for sure. I think the author should just have zoomed in/out or maybe stepped back before shooting .. i think that is the mess with hires sensors without low pass filters in the optics.

I also have not read anything how to fix that afterwards by algo, anyone can enlighten me?

**Comment by AxelG-DE** [comment]
> But hey - Let's be happy that @jenshannoschwalm introduced RCD to darktable!

Ooops, I hope I didn't use wrong tone or "topic colorization" :blush:
Yes, thank you very much to @jenshannoschwalm for implementing RCD. I will definitely test it in depth. Next with my OMD EM-5 II pics
Also I want to send my great appreciation to @heckflosse, who looks a lot across the borders (ueber den Tellerrand, as we have the saying). 
All your guys efforts are very much appreciated!

**Comment by jenshannoschwalm** [comment]
@AxelG-DE "Alles jut, null Problemo" :-)

BTW i am very interested in your experience with your images. But this should be discussed elswhere...
