### ISSUE TITLE
git master : commit 2da359d : compile error : Debian stable

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#17182]
### Describe the bug

Make fails after commit https://github.com/darktable-org/darktable/commit/2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b.

### Steps to reproduce

Build darktable git master:
```
git clone https://github.com/darktable-org/darktable.git
cd darktable
git submodule update --init
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/usr/source/darktable/install -DCMAKE_BUILD_TYPE=Release ..
make 
```
I get this error:
```
...
[ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c:113:10: error: void value not ignored as it ought to be
  113 |   result = avifRGBImageAllocatePixels(&rgb);
      |          ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2238: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2494: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

### Expected behavior

Darktable should build. The commit up to and including https://github.com/darktable-org/darktable/commit/517889efe01b9626a82e98021df670d7c5bf7c94 was fine

### Commit

https://github.com/darktable-org/darktable/comm2da359d5b683eb0f9ab8a280a0626e9ec53e9e9bit/ beaks build.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

release-4.9.0-73-g2da359d5b6, built from source

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable bookworm 12.6.

### Describe your system?

- OS : Linux debian 6.1.0-23-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
- Linux - Distro : Debian 12.6 Stable Bookworm
- Memory : 64 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : NVIDIA 535.183.01 from Debian non-free repo
- OpenCL installed : Yes,   OpenCL 3.0 CUDA 12.2.148
- OpenCL activated : Yes (but --disable-opencl does not help, same issue)
- Xorg : X11
- Desktop : Gnome 43.9
- GTK:  3.24.38-2~deb12u1, 4.8.3+ds-2+deb12u1, 2.24.33-2
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release
- Intel® Core™ i9-14900K × 32
- motherboard: ASUS PRIME Z790-A WIFI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000], NVIDIA 535.183.01 from Debian non-free repo

**Comment by ptilopteri** [comment]
* Magnus Larsson ***@***.***> [07-21-24 15:35]:
> ### Describe the bug
> 
> Make fails after commit https://github.com/darktable-org/darktable/commit/2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b.
> 
> ### Steps to reproduce
> 
> Build darktable git master:
> ```
> git clone https://github.com/darktable-org/darktable.git
> cd darktable
> git submodule update --init
> mkdir build && cd build
> cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/usr/source/darktable/install -DCMAKE_BUILD_TYPE=Release ..
> make 
> ```
> I get this error:
> ```
> ...
> [ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o
> /home/magnus/usr/source/darktable/src/imageio/imageio_avif.c: In function ‘dt_imageio_open_avif’:
> /home/magnus/usr/source/darktable/src/imageio/imageio_avif.c:113:10: error: void value not ignored as it ought to be
>   113 |   result = avifRGBImageAllocatePixels(&rgb);
>       |          ^
> compilation terminated due to -Wfatal-errors.
> make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2238: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2494: bin/CMakeFiles/lib_darktable.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2

just successfully build on openSUSE Tumbleweed
release-4.9.0-73-g2da359d5b6


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by victoryforce** [comment]
> Debian stable bookworm 12.6.

@KarlMagnusLarsson What is your libavif version? I assume 0.11.1 right?

**Comment by KarlMagnusLarsson** [comment]
> > Debian stable bookworm 12.6.
> 
> @KarlMagnusLarsson What is your libavif version? I assume 0.11.1 right?

Yes, libavif-dev/stable,now 0.11.1-1 amd64 [installed]

It seems the interface to avifRGBImageAllocatePixels has changed.

**Comment by victoryforce** [comment]
> It seems the interface to avifRGBImageAllocatePixels has changed.

Yes. They break ABI in 1.0.0. I'll make a fix.

**Comment by KarlMagnusLarsson** [comment]
I can confirm that I can build with libavif from libavif master branch (I did not enable any codes though, in my local libavif build).

**Comment by victoryforce** [comment]
@KarlMagnusLarsson Please make sure you are building with the system libavif (ie version 0.11.1) and test the PR linked above if you can.

**Comment by KarlMagnusLarsson** [comment]
Hello @victoryforce ,

Thank you for the PR. Now I get:
```
 83%] Building C object lib/darktable/plugins/imageio/format/CMakeFiles/avif_format.dir/avif.c.o
/home/magnus/test/darktable-test/darktable/src/imageio/format/avif.c: In function ‘write_image’:
/home/magnus/test/darktable-test/darktable/src/imageio/format/avif.c:380:14: error: void value not ignored as it ought to be
  380 |       result = avifImageSetProfileICC(image, icc_profile_data, icc_profile_len);
      |              ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib/darktable/plugins/imageio/format/CMakeFiles/avif_format.dir/build.make:76: lib/darktable/plugins/imageio/format/CMakeFiles/avif_format.dir/avif.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7174: lib/darktable/plugins/imageio/format/CMakeFiles/avif_format.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by victoryforce** [comment]
In order not to do several iterations, can I ask you to remove the assignment of the result of the function (`result =`) from the line that the compiler complained about and try to compile again? So you will be able to find out if there are other places with such a change in ABI functions.

**Comment by KarlMagnusLarsson** [comment]
Your PR works for me (compiles, installs and starts, I have not tested more that that), with these ADDITONAL changes:
```diff
git diff
diff --git a/src/imageio/format/avif.c b/src/imageio/format/avif.c
index 4f7eb3a832..f4b8a0ae40 100644
--- a/src/imageio/format/avif.c
+++ b/src/imageio/format/avif.c
@@ -377,7 +377,7 @@ int write_image(struct dt_imageio_module_data_t *data,
         goto out;
       }
       cmsSaveProfileToMem(cp->profile, icc_profile_data, &icc_profile_len);
-      result = avifImageSetProfileICC(image, icc_profile_data, icc_profile_len);
+      avifImageSetProfileICC(image, icc_profile_data, icc_profile_len);
       if(result != AVIF_RESULT_OK)
       {
         dt_print(DT_DEBUG_IMAGEIO, "avifImageSetProfileICC failed\n");
@@ -406,7 +406,7 @@ int write_image(struct dt_imageio_module_data_t *data,
   avifRGBImageSetDefaults(&rgb, image);
   rgb.format = AVIF_RGB_FORMAT_RGB;
 
-  result = avifRGBImageAllocatePixels(&rgb);
+  avifRGBImageAllocatePixels(&rgb);
   if(result != AVIF_RESULT_OK)
   {
     dt_print(DT_DEBUG_IMAGEIO, "avifRGBImageAllocatePixels failed\n");
@@ -476,7 +476,7 @@ int write_image(struct dt_imageio_module_data_t *data,
   /* TODO: workaround; remove when exiv2 implements AVIF write support and use dt_exif_write_blob() at the end */
   if(exif && exif_len > 0)
   {
-    result = avifImageSetMetadataExif(image, exif, exif_len);
+    avifImageSetMetadataExif(image, exif, exif_len);
     if(result != AVIF_RESULT_OK)
     {
       dt_print(DT_DEBUG_IMAGEIO, "avifImageSetMetadataExif failed\n");
@@ -492,7 +492,7 @@ int write_image(struct dt_imageio_module_data_t *data,
     size_t xmp_len;
     if(xmp_string && (xmp_len = strlen(xmp_string)) > 0)
     {
-      result = avifImageSetMetadataXMP(image, (const uint8_t *)xmp_string, xmp_len);
+      avifImageSetMetadataXMP(image, (const uint8_t *)xmp_string, xmp_len);
       g_free(xmp_string);
       if(result != AVIF_RESULT_OK)
       {
```

**Comment by victoryforce** [comment]
OK, great, thanks for the help @KarlMagnusLarsson! I'll make the corresponding additions to the PR tomorrow (it's already after midnight in Kyiv, plus there's going to be a power outage soon).

**Comment by KarlMagnusLarsson** [comment]
Hej @victoryforce, OK, it is late in Stockholm Sweden as well.  

Technically, I could use my own local libavif, in case you decide to raise minimum libavif version requirement for darktable build, instead.

**Comment by wpferguson** [comment]
breaks 22.04 with libavif 0.9.3-3

**Comment by victoryforce** [comment]
> Technically, I could use my own local libavif, in case you decide to raise minimum libavif version requirement for darktable build, instead.

Yes, you could, but the correct solution should satisfy all users of distros with libavif before 1.0.0. There is no need to raise the library version requirement, the source code can provide (by conditional compilation) support for both ABIs.

I added to the PR the fixes that were missing in the first version, it should now actually compile on Debian 12 (and all distros with old libavif). Also, Hanno suggested a slightly different way to fix the source code. I'm not sure which way will make the code clearer for the reader (simply show the ABI difference between the library versions where the function is called or hide it behind a trick function-replacing macro that is defined in the header file)... In the end, Pascal will choose one of the two PRs and merge it.

**Comment by KarlMagnusLarsson** [comment]
> I added to the PR the fixes that were missing in the first version, it should now actually compile on Debian 12 (and all distros with old libavif). Also, Hanno suggested a slightly different way to fix the source code. I'm not sure which way will make the code clearer for the reader (simply show the ABI difference between the library versions where the function is called or hide it behind a trick function-replacing macro that is defined in the header file)... In the end, Pascal will choose one of the two PRs and merge it.

Both PRs work for me. Thank you @victoryforce and @jenshannoschwalm.

- https://github.com/darktable-org/darktable/pull/17183
- https://github.com/darktable-org/darktable/pull/17184
