### PR TITLE
Fix avif building issues

### LINKED ISSUE #17182: git master : commit 2da359d : compile error : Debian stable
### Describe the bug

Make fails after commit https://github.com/darktable-org/darktable/commit/2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b.

### Steps to reproduce

Build darktable git master:
```
git clone https://github.com/darktable-org/darktable.git
cd darktable
git submodule update --init
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/usr/source/darktable/install -DCMAKE_BUILD_TYPE=Release ..
make 
```
I get this error:
```
...
[ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c:113:10: error: void value not ignored as it ought to be
  113 |   result = avifRGBImageAllocatePixels(&rgb);
      |          ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2238: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2494: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

### Expected behavior

Darktable should build. The commit up to and including https://github.com/darktable-org/darktable/commit/517889efe01b9626a82e98021df670d7c5bf7c94 was fine

### Logfile | Screenshot | Screencast

_No response_

### Commit

https://github.com/darktable-org/darktable/comm2da359d5b683eb0f9ab8a280a0626e9ec53e9e9bit/ beaks build.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

release-4.9.0-73-g2da359d5b6, built from source

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable bookworm 12.6.

### Describe your system?

- OS : Linux debian 6.1.0-23-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
- Linux - Distro : Debian 12.6 Stable Bookworm
- Memory : 64 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : NVIDIA 535.183.01 from Debian non-free repo
- OpenCL installed : Yes,   OpenCL 3.0 CUDA 12.2.148
- OpenCL activated : Yes (but --disable-opencl does not help, same issue)
- Xorg : X11
- Desktop : Gnome 43.9
- GTK:  3.24.38-2~deb12u1, 4.8.3+ds-2+deb12u1, 2.24.33-2
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release
- Intel® Core™ i9-14900K × 32
- motherboard: ASUS PRIME Z790-A WIFI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000], NVIDIA 535.183.01 from Debian non-free repo

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Instead of multiple checks all over the avif code this adds some simple macros depending on avif version and makes use of them.

Fixes #17182  (i think so, @wpferguson @KarlMagnusLarsson can you confirm it builds for you too)

### CODE REVIEW

**Comment by KarlMagnusLarsson** [comment]
Hello @jenshannoschwalm,

Compiles and runs on Debian 12.6 with libavif-dev/stable 0.11.1-1 amd64.

I have also tested with some actual avif picture files. Works fine in lighttable and darkroom. The import function could not generate a preview, though. All I got was a darktable icon.

File: src/imageio/imageio_avif.h [hunk 1]
```diff
@@ -21,6 +21,20 @@
...
 #include "common/mipmap_cache.h"
 
+#if AVIF_VERSION > 110100
+  #define DT_avifImageSetProfileICC avifImageSetProfileICC
+  #define DT_avifRGBImageAllocatePixels avifRGBImageAllocatePixels
+  #define DT_avifImageSetMetadataExif avifImageSetMetadataExif
+  #define DT_avifImageSetMetadataXMP avifImageSetMetadataXMP
+  #define DT_avifImageRGBToYUV avifImageRGBToYUV
+#else
+  #define DT_avifImageSetProfileICC AVIF_RESULT_OK; avifImageSetProfileICC
```
Comment (ralfbrown) [inline src/imageio/imageio_avif.h:31]: These macros are quite brittle, e.g. you couldn't use the function call as part of the condition in an `if` statement.  I would have made them inline functions.

Comment (jenshannoschwalm) [reply src/imageio/imageio_avif.h:31]: We now have three pr's for this issue. I think it's better to have fixes either via macros or inlines than spread over the code. You wanna take over?

**Comment by jenshannoschwalm** [comment]
Closing this as two pr's on the same  subject are by far enough :-)
