### ISSUE TITLE
Unable to build current master (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#7991]
**Describe the bug**
Current master doesn't build.

```
[ 33%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imagebuf.c.o
/home/jade/.local/git/darktable/src/common/exif.cc: In function 'int dt_exif_xmp_attach_export(int, const char*, void*)':
/home/jade/.local/git/darktable/src/common/exif.cc:4009:29: error: 'kerTooLargeJpegSegment' is not a member of 'Exiv2'
       if(e.code() == Exiv2::kerTooLargeJpegSegment)
                             ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:368: bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1592: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**To Reproduce**
1. Pull/clone
2. Start build process
3. Doesn't finish

**Expected behavior**
To build cleanly.

**Bisect**

```
[stasis] jade ~/.local/git/darktable $ git bisect good
6c3ea20c3961fd924bd49dc973e0b3dd9a80a515 is the first bad commit
commit 6c3ea20c3961fd924bd49dc973e0b3dd9a80a515
Author: phweyland <philippe.weyland@laposte.net>
Date:   Sat Jan 23 12:44:22 2021 -0300

    export metadata: remove history from xmp if max size exceeded
    
    fixes #4355

:040000 040000 bc1a009385273bb844f2f035aaa1fca2a554a981 f05a7ec8b15a89cfa3e8e1d3fcf05aa0b0930892 M      src
```

* darktable version : 3.5.0+817 gba3ce374e / 3.4.0 

**Platform**

* OS                : Linux (kernel 5.8.10-1)
* Distro            : Debian Buster (rel. 10.7)
* Graphics driver   : nvidia (450.80.02)
* OpenCL installed  : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk+          : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB
* Memory           : 32 Gb + 15 Gb Swap

**Additional context**

[dt.build.2021.01.25.0859.log](https://github.com/darktable-org/darktable/files/5868145/dt.build.2021.01.25.0859.log)

Ping @phweyland 

EDIT: Added correct logfile

**Comment by johnny-bit** [comment]
Since CI builds that without problem I need to assume it's some problem with Exiv2 version... so... What's your Exiv2 version?

**Comment by jade-nl** [comment]
I'm using the one that comes with the current stable Debian:

```
[stasis] jade ~ $ exiv2 --version
exiv2 0.25 001900 (64 bit build)

```

**Comment by johnny-bit** [comment]
Well... Shit.

The `kerTooLargeJpegSegment` was added to Exiv2 in https://github.com/Exiv2/exiv2/pull/109

before that the error code was... `37` (as in integer number 37) as can be seen in
https://github.com/Exiv2/exiv2/blob/d897997b29464b775d52e324769d1e762586f8d2/src/jpgimage.cpp#L1047

@phweyland - can we do similar check to what was done for sqlite and in case ofold exiv2 use code `37` and for newer ones use the `kerTooLarge...`?

**Comment by jade-nl** [comment]
I just build and installed the latest exiv2 (git master), which would be:

```
[stasis] jade ~ $ which exiv2
/usr/local/bin/exiv2
[stasis] jade ~ $ exiv2 --version
exiv2 0.27.99.0
```

darktable does build cleanly with that one.

**Comment by parafin** [comment]
Yeah, it's better to check for exiv2 version and use 37 for older releases.

**Comment by phweyland** [comment]
> can we do similar check to what was done for sqlite and in case ofold exiv2 use code `37` and for newer ones use the `kerTooLarge...`

Sure. I'll do it.
