### PR TITLE
import&copy: keep the original access and modified timestamps

### LINKED ISSUE #12355: The "copy&import" operation results in a change in the date and time of the raw file.
I have posted this issue in Pixel.us, and I have been suggested to open an issue here. Maybe @phweyland could give some help.

When copying images (RAW format) from the memory card, using the “copy&import” option, DT changes the original date and time of the raw file (when the picture was taken), to the date and time of the moment the images are being imported into DT. Certainly in the file properties, in the left pane of DT, it does recognize the original date. So, it does not appear to have modified the exif data inside the raw. There is no problem. The problem is in the date of the file itself after copying it.

It is curious that when the pictures are taken with the RAW+JPG option, the copied RAW files have their time and date modified, but not the JPG files. This does not happen when I use another program to copy the photos from the memory card and then import them with DT.

This happens regardless of the version of DT (3.8, 4.0, 4.1 develop. build) or the version of Windows (10 or 11), but always Windows.

I attach some screenshots…

This is on the memory card. The date and time are those of the moment the photo was taken:
imagen

This is the setup used to copy&import:
imagen

… and this is the result on the destination folder:
imagen

You can appreciate that the date of the JPG file has been preserved, but the date of the RAW file has been changed to that of the moment it was transferred.

**Platform:**
* darktable version : 3.8, 4.0, 4.1 develop. build
* OS                : Win10 or 11

**Additional context:**
 - Do you use lua scripts? No, only the "copy&import" module

Thank you in advance!

### PR DESCRIPTION
**Pull request by phweyland**
partially fixes #12355

EDITED
The lazy one: on windows the code is still to be written

Replaces #12357

### CODE REVIEW

**Comment by TurboGit** [comment]
@phweyland : Have you tested on Windows? Just asking as the CI seems highly confused with Windows build at the moment and I'm not a Windows guy, so cannot test on my side. TIA.

**Comment by phweyland** [comment]
> Have you tested on Windows?

No, I cannot neither.
But CI gives a new issue utimes() is not available (on windows I guess). But utime() should exists. I do it.

**Comment by TurboGit** [comment]
Ok, so please if a Windows user can help here by testing this PR and/or a modified version of it if it does not compile it would be greatly appreciated. TIA.

@gi-man : Maybe you can help?

**Comment by phweyland** [comment]
The CI error seems to have gone ...

**Comment by gi-man** [comment]
HEAD is now at 5ea47dc5a

```
C:/msys64/home/gman/test/darktable/src/control/jobs/control_jobs.c:2113:19: error: incompatible type for argument 2 of 'utime'
 2113 |     utime(output, times); // set origin file timestamps
      |                   ^~~~~
      |                   |
      |                   struct utimbuf

```

**Comment by phweyland** [comment]
> HEAD is now at [5ea47dc](https://github.com/darktable-org/darktable/commit/5ea47dc5a5a97fa9d5d6379552962492dac205f9)

What do you mean ? Is there an issue there ?

Pascal, what I can do is to remove the WIN32 code and let someone with access to windows dev end the job ...

**Comment by gi-man** [comment]
I wasnt clear. It failed to build on the current UCRT environment/packages. I think utime.h is not available in the current library packages we use. @kmilos thoughts?

**Comment by phweyland** [comment]
I've removed the WIN32 part. It was (in case it could help):

    struct utimbuf times;
    times.actime = statbuf.st_atime;
    times.modtime = statbuf.st_mtime;
    utime(output, times); // set origin file timestamps

**Comment by kmilos** [comment]
Unfortunately not near mydev machine for a while to check the UCRT status...

**Comment by TurboGit** [comment]
@kmilos : I have assigned this to you for the UCRT possible missing package. TIA.

**Comment by kmilos** [comment]
> I think utime.h is not available in the current library packages we use.

[It is available from mingw-w64-headers, which should be installed as part of the toolchain](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-headers-git?repo=ucrt64).

I wonder if some of the defined macros are creating some issue for the exported symbols though: https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/crt/sys/utime.h

**Comment by kmilos** [comment]
@phweyland It looks like on Windows we only have seconds precision and the first utime() call:

https://man7.org/linux/man-pages/man2/utime.2.html

so you'd need to create this `utimbuf` struct which has two `time_t` fields before calling `utime()` instead of `utimes()` on other platforms.

**Comment by TurboGit** [comment]
@phweyland : Just to be sure there was no quirk on your side. Just after @kmilos suggestion you have pushed some changes but this does not have the `_WIN32` part as proposed.

**Comment by phweyland** [comment]
> you have pushed some changes but this does not have the `_WIN32` part as proposed

Indeed! Sorry. I hope this is ok now.

**Comment by kmilos** [comment]
Still missing.

**Comment by phweyland** [comment]
> Still missing.

Sorry again, I'd skipped your message, :(
Introducing your proposal.

**Comment by kmilos** [comment]
Windows CI is green @TurboGit

**Review by TurboGit — APPROVED** [review]
Thanks for the cooperation here!

**Comment by WMAM** [comment]
Thank you so much!

**Comment by TurboGit** [comment]
@phweyland : This does not merge (conflicts) on darktable-4.0.1 branch. I'm proposing to also cherry-pick 9418b748c300c63800ac9bfd7b1f848d82cd62b4 (variable MAKER & MODEL at import), ok for you? Otherwise we need to create a specific patch for 4.0.1 branch for this PR. What do you think?

**Comment by kmilos** [comment]
I'd test the nightly tomorrow before 4.0.1 tagging though 😉

**Comment by phweyland** [comment]
> I'm proposing to also cherry-pick 9418b748c300c63800ac9bfd7b1f848d82cd62b4 (variable MAKER & MODEL at import), ok for you?

That's ok for me, sure !

**Comment by TurboGit** [comment]
Done ! So 4.0.1 should be almost ready now.

**Comment by kmilos** [comment]
@WMAM Can you please confirm w/ the [last nightly build](https://github.com/darktable-org/darktable/actions/runs/3004217073)?

**Comment by WMAM** [comment]
@kmilos Sorry for being late. We are on Pacific time, and I can barely see your message. Yes, I worked with that build last night and it worked perfectly.
Thank you so much!

**Comment by MStraeten** [comment]
breaks osx build:
```
[ 43%] Building C object bin/CMakeFiles/lib_darktable.dir/develop/blend.c.o
/Users/martinstraeten/src/darktable/src/control/jobs/control_jobs.c:2124:37: fatal error: no member named 'st_atim' in 'struct stat'
    times[0].tv_sec = (long)statbuf.st_atim.tv_sec;
                            ~~~~~~~ ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/control/jobs/control_jobs.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```
git bisect bad
62c20f8a233e91706c31d01b8f107b7868f5a290 is the first bad commit
commit 62c20f8a233e91706c31d01b8f107b7868f5a290
Author: phweyland <philippe.weyland@laposte.net>
Date:   Mon Aug 22 16:39:25 2022 -0300

    import&copy: keep the original access and modified timestamps

    partially (on linux) fixes #12355

 src/control/jobs/control_jobs.c | 25 ++++++++++++++++++++-----
 1 file changed, 20 insertions(+), 5 deletions(-)
