### ISSUE TITLE
Git-master : Compile error : imageio_pfm.c:129:7: error: not enough perfectly nested loops before ‘const’

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#18742]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

I get a compilation error when compiling git master:
```
/home/magnus/test/darktable-test/darktable/src/imageio/imageio_pfm.c: In function ‘dt_imageio_open_pfm’:
/home/magnus/test/darktable-test/darktable/src/imageio/imageio_pfm.c:129:7: error: not enough perfectly nested loops before ‘const’
  129 |       const size_t target_row = made_by_photoshop ? row : img->height - 1 - row;
      |       ^~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2070: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_pfm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2542: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Steps to reproduce

1. Checkout git master
2. cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/test/darktable-test/install -DCMAKE_BUILD_TYPE=Release ..
3. make -j32

```
/home/magnus/test/darktable-test/darktable/src/imageio/imageio_pfm.c: In function ‘dt_imageio_open_pfm’:
/home/magnus/test/darktable-test/darktable/src/imageio/imageio_pfm.c:129:7: error: not enough perfectly nested loops before ‘const’
  129 |       const size_t target_row = made_by_photoshop ? row : img->height - 1 - row;
      |       ^~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2070: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_pfm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2542: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

### Expected behavior

Sucessful build.

### Logfile | Screenshot | Screencast

Git bisect result:
```
39b5e3609c87be5f8a25a704cfb42ead7caa5c2b is the first bad commit
commit 39b5e3609c87be5f8a25a704cfb42ead7caa5c2b
Author: Hanno Schwalm <hanno@schwalm-bremen.de>
Date:   Sat Apr 26 08:20:47 2025 +0200

    Imageio PFM fixes
    
    1. Allocate temp buffer only for what we need
    2. Check for correct size of read data from file and possibly report as corrupted
    3. some constify and simplifications

 src/imageio/imageio_pfm.c | 51 +++++++++++++++++++----------------------------
 1 file changed, 21 insertions(+), 30 deletions(-)
```

### Commit

39b5e3609c87be5f8a25a704cfb42ead7caa5c2b

### Where did you obtain darktable from?

self compiled

### darktable version

release-5.1.0-694-g39b5e3609c

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable 12.10 Bookworm

### Describe your system

gcc version 12.2.0 (Debian 12.2.0-14) 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Not relevant here.

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Readme states:

Dependencies

Compatible compilers/toolchains:

    Clang: 15 and later
    GCC: 12 and later
    MinGW-w64: 10 and later
    XCode: 15.2 and later

**Comment by KarlMagnusLarsson** [comment]
This is compiler version related.

- gcc-12.2.0 does not work for me
- gcc 13.2.0 does not work
- gcc 14.1.0 works

The readme states GCC 12 and later, but I have to compile with gcc-14.1 to be able to compile commit https://github.com/darktable-org/darktable/commit/39b5e3609c87be5f8a25a704cfb42ead7caa5c2b.

It looks like, but I do not know for sure, that darktable use gcc version 15 for CI.

**Comment by ralfbrown** [comment]
The fix is to remove the "collapse(2)" from the DT_OMP_FOR() a couple of lines above.  The "collapse" directive requires that the outer loop contains no code except the inner loop.  GCC 14+ might be optimizing away the offending line....

**Comment by KarlMagnusLarsson** [comment]
Hello @ralfbrown,

Thank you for the fix. Do you mean this?
```diff
diff --git a/src/imageio/imageio_pfm.c b/src/imageio/imageio_pfm.c
index 48370da99b..8381d826ef 100644
--- a/src/imageio/imageio_pfm.c
+++ b/src/imageio/imageio_pfm.c
@@ -123,7 +123,7 @@ dt_imageio_retval_t dt_imageio_open_pfm(dt_image_t *img,
   // the rows in the process of filling the output buffer with data
   if(channels == 3)
   {
-    DT_OMP_FOR(collapse(2))
+    DT_OMP_FOR() // WORKAROUND: remove collapse(2) from DT_OMP_FOR(collapse(2))
     for(size_t row = 0; row < img->height; row++)
     {
       const size_t target_row = made_by_photoshop ? row : img->height - 1 - row;
```
I still get the same error when compiling with gcc 12.2.0. I am misunderstanding the fix?

**Comment by ralfbrown** [comment]
There's a second occurrence which needs to be edited later in the function.

**Comment by wpferguson** [comment]
Commenting out both instances works for me.

**Comment by ralfbrown** [comment]
Fixed by https://github.com/darktable-org/darktable/commit/9bb5b2f221a3750dcdc424b9af4bb1d68af46d7b

**Comment by KarlMagnusLarsson** [comment]
Hello @ralfbrown,

Works for me. Thank you.
