### ISSUE TITLE
Compilation doesn't work

### ISSUE THREAD

**Issue by hgmarty** [darktable-org/darktable#6331]
Hello,

with the commit a7eb82d8523520ba7541e2255a95d245dcc862ba by @TurboGit , i have an error stops the compilation.

`[ 49%] Linking C shared module libexport.so
[ 49%] Built target filter
[ 49%] Built target copy_history
[ 49%] Linking C shared module libhistory.so
/home/guillaume/git-darktable/src/libs/import.c: In function ‘_lib_import_get_extra_widget’:
/home/guillaume/git-darktable/src/libs/import.c:366:14: error: ‘main’ is usually a function [-Werror=main]
   GtkWidget *main = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
              ^~~~
[ 49%] Built target modulelist
[ 49%] Linking C shared module liblighttable_mode.so
[ 49%] Linking C shared module libnavigation.so
cc1: all warnings being treated as errors
make[2]: *** [src/libs/CMakeFiles/import.dir/build.make:63: src/libs/CMakeFiles/import.dir/import.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3245: src/libs/CMakeFiles/import.dir/all] Error 2
make[1]: *** Attente des tâches non terminées....
[ 49%] Built target export
[ 49%] Built target snapshots
[ 49%] Built target lighttable_mode
[ 49%] Built target history
[ 49%] Built target navigation
make: *** [Makefile:152: all] Error 2
`

I am with Debian Buster. I compil dt with the the script in git and :
`libgtk-3-dev:
  Installé : 3.24.5-1
  Candidat : 3.24.5-1
 Table de version :
 *** 3.24.5-1 500
        500 http://ftp.fr.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status`

Is it ths version what is too low ?
Do you need other infos ?

Thanks for your return

**Comment by jade-nl** [comment]
Came here to report this and found this thread.

A git bisect shows this:

```
a7eb82d8523520ba7541e2255a95d245dcc862ba is the first bad commit
commit a7eb82d8523520ba7541e2255a95d245dcc862ba
Author: Pascal Obry <pascal@obry.net>
Date:   Fri Sep 18 18:54:13 2020 +0200

    import dialog - split in two columns the main options and metadata.

:040000 040000 b232beb02ae690e5df5f6f996d152e9e8b85d0ca 264b22aeceba4d6c360883a44ff976edee3dac79 M      src
```

Some local info:

**Platform**
* darktable        : 3.3.0+775 g247b82076
* OpenCL installed : Yes (nvidia-opencl-common 440.100-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER7979 MiB
* Graphics driver  : nvidia (440.100)
* OS               : Linux (kernel 5.7.10-1)
* Distro           : Debian Buster (rel. 10.5)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Error show while compiling**
[ 51%] Built target location
[ 51%] Built target recentcollect
Scanning dependencies of target modulelist
Scanning dependencies of target copy_history
[ 53%] Building C object src/libs/CMakeFiles/modulelist.dir/modulelist.c.o
/home/jade/.local/git/darktable/src/libs/import.c: In function '_lib_import_get_extra_widget':
/home/jade/.local/git/darktable/src/libs/import.c:366:14: error: 'main' is usually a function [-Werror=main]
   GtkWidget *main = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
              ^~~~
[ 54%] Building C object src/libs/CMakeFiles/copy_history.dir/copy_history.c.o
Scanning dependencies of target snapshots
[ 54%] Built target histogram
[ 54%] Building C object src/libs/CMakeFiles/snapshots.dir/snapshots.c.o
[ 54%] Linking C shared module libcollect.so
Scanning dependencies of target export
cc1: all warnings being treated as errors
make[2]: *** [src/libs/CMakeFiles/import.dir/build.make:63: src/libs/CMakeFiles/import.dir/import.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3245: src/libs/CMakeFiles/import.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 56%] Building C object src/libs/CMakeFiles/export.dir/export_metadata.c.o

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by jade-nl** [comment]
Yep, fixed.

Thanks!

**Comment by hgmarty** [comment]
Thanks Pascal, it works.
