### ISSUE TITLE
Building: Yet another GCC vs CLANG compile problem (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#8231]
**Describe the bug**
darktable, latest master, fails to build when using gcc.

```
[ 98%] Building C object bin/chart/CMakeFiles/darktable-chart.dir/deltaE.c.o
[ 98%] Building C object bin/chart/CMakeFiles/darktable-chart.dir/pfm.c.o
[ 98%] Linking C shared module libpiwigo.so
/home/jade/.local/git/darktable/src/chart/main.c: In function 'get_xyz_sample_from_image':
/home/jade/.local/git/darktable/src/chart/main.c:1534:9: error: 'delta_x_top' is predetermined 'shared' for 'shared'
   shared(corners, x_start, y_start, x_end, y_end, delta_x_top, delta_y_top, \
         ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/chart/CMakeFiles/darktable-chart.dir/build.make:63: bin/chart/CMakeFiles/darktable-chart.dir/main.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

It does build when using clang instead.

**To Reproduce**
1. Clone/Pull darktable
2. Start building process (using gcc)

**Expected behaviour**
Build cleanly.

**Bisect**

```
b6b4928c568bd1284d09833e5d0c3e695a958c5b is the first bad commit
commit b6b4928c568bd1284d09833e5d0c3e695a958c5b
Author: Pascal Obry <pascal@obry.net>
Date:   Sun Feb 14 23:10:17 2021 +0100

    Minor code clean-up.

:040000 040000 6c9cfabcbe2fa0d1b8e41fd67afa74b5cdb36276 fc3815e33ebf7588e0d7b49a0c84de533489b6c1 M      src
```

Not entirely sure about the outcome of the above bisect. Did it twice though, both came out the same.

Anyway: Pinging @TurboGit 

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.8)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.99.0
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by ralfbrown** [comment]
@TurboGit  fixed in 36f85c849f84a6996c76eb02c6ebff9f6f2e82c7 if you want to cherry-pick.

**Comment by TurboGit** [comment]
@ralfbrown : Thanks, cherry-picked.
