### ISSUE TITLE
breaks osx build:

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12446]
breaks osx build:
```
[ 43%] Building C object bin/CMakeFiles/lib_darktable.dir/develop/blend.c.o
/Users/martinstraeten/src/darktable/src/control/jobs/control_jobs.c:2124:37: fatal error: no member named 'st_atim' in 'struct stat'
    times[0].tv_sec = (long)statbuf.st_atim.tv_sec;
                            ~~~~~~~ ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/control/jobs/control_jobs.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```
git bisect bad
62c20f8a233e91706c31d01b8f107b7868f5a290 is the first bad commit
commit 62c20f8a233e91706c31d01b8f107b7868f5a290
Author: phweyland <philippe.weyland@laposte.net>
Date:   Mon Aug 22 16:39:25 2022 -0300

    import&copy: keep the original access and modified timestamps

    partially (on linux) fixes #12355

 src/control/jobs/control_jobs.c | 25 ++++++++++++++++++++-----
 1 file changed, 20 insertions(+), 5 deletions(-)

_Originally posted by @MStraeten in https://github.com/darktable-org/darktable/issues/12367#issuecomment-1240936935_

**Comment by TurboGit** [comment]
@MStraeten : Any idea to fix that? We need a MacOS dev here to help. TIA.

**Comment by kmilos** [comment]
Just missing "e" at the end for the two fields:

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/stat.2.html

We also need someone to take better care of the macOS CI... 😒

**Comment by victoryforce** [comment]
> We also need someone to take better care of the macOS CI... 😒

I will try to revive it (even though I am not an apple person). Anyway, it looks like it's pretty obvious which command causes CI to fail on insall deps step. I can only cross my fingers and hope that this fix will be enough.

**Comment by TurboGit** [comment]
Fixed yesterday.

**Comment by kmilos** [comment]
@TurboGit Missing from 4.0.1 tag AFAICT?

**Comment by TurboGit** [comment]
> @TurboGit Missing from 4.0.1 tag AFAICT?

Sad but true... Don't know what happened, it is properly tagged for 4.0.1 but looks like I did not cherry-picked it :(

@parafin: You'll need this for the build.

**Comment by kmilos** [comment]
You can re-tag if it's not too late....

**Comment by TurboGit** [comment]
It is too late, tarball created and signed and Linux binaries ready :)
