### PR TITLE
gui: keep background jobs on GTK thread and avoid Windows attention spam

### LINKED ISSUE #21829: Darktable on Windows steals focus each time a progress message pops-up
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When I batch export images, each time a progress message ("x/y exported to") pops-up, darktable grabs the focus. This happens within the same virtual desktop, or across different virtual desktops. This is very annoying, as you cannot do anything in the other virtual desktop, as the desktop changes after some seconds. Also, if you try to type something in one window, you are suddenly giving random keyboard shortcuts to darktable.

### Steps to reproduce

1. Start darktable from the .exe file
2. Export multiple images
3. Change focus to another window or virtual desktop
4. See focus been grabbed when a new message "x/y exported to <dir>/file.jpg"

### Expected behavior

If user moves the input focus to another window, it should stay there.

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

self compiled

### darktable version

5.7.0+442~g2067984726

### What OS are you using?

Windows

### What is the version of your OS?

Win11 Enterprise

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia T500

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

If I start dt with a PowerShell script
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -WindowStyle Hidden -command "& 'C:\Program Files\darktable\bin\darktable.exe' *>&1"`
dt doesn't grab the focus.

### PR DESCRIPTION
**Pull request by Arecsu**
Fixes #21829

The background-jobs panel was creating GTK widgets from worker threads and only queueing their packing/showing. This made widget creation, progress updates, and teardown timing-dependent, contributing to platform-specific focus problems.

The panel now keeps worker callbacks GTK-free: they update plain state, while widget creation, updates, cancellation controls, and removal run on the GTK thread. Queued callbacks also keep job data alive and are invalidated during cleanup.

On Windows, repetitive background status overlays are suppressed when they can appear after focus has moved away from darktable:

- **Exports:** per-image success and skip overlays are suppressed for disk, gallery, LaTeX, email, and Piwigo exports. The background-jobs panel still shows `exporting X / N to <storage>` together with the progress bar.
- **Imports:** per-image camera-import overlays and the final batch summary for regular imports are suppressed. The background-jobs panel still shows the import status and updates its progress bar as images are imported.
- **Immediate and actionable messages:** messages such as `no image to export`, import-start messages, and errors remain visible. Linux and macOS keep their original log-overlay behavior.
- **Completion notification:** where the job uses `dt_ui_notify_user()`, the one-time completion notification remains enabled. It is not triggered once per image.

This is a deliberate workaround: I could not find a clean GTK3/Win32 way to show the per-image status overlay without triggering taskbar attention. The sidebar provides the same useful progress information without using `dt_control_log()` for those repetitive updates. There should be one, but we need to dig further on this

Linux GTK3 builds and cancellation/lifecycle stress tests pass. Windows 11 testing confirms no per-image flashing or focus stealing during export while preserving the batch-completion notification.

Related: #21843

### CODE REVIEW

**Comment by Arecsu** [comment]
@lintujuh & @thanatomanic

if you can test this one, this might finally fix the focus stealing in Windows when exporting. I don't have a Windows machine yet to test this myself

@TurboGit I've tested possible regressions under Linux, creating many batched exports, canceling, creating them, etc, and everything seems fine so far. Just mentioning in case you might want to check it for yourself, that is what should be tested

**Comment by Thanatomanic** [comment]
@Arecsu I'm afraid this has not solved the focus stealing for me on Windows 10 (during export nor import), building on an updated MSYS2 environment.

Are there more diagnostics I can provide you, like which gtk libs and other versions were used to build? I could potentially try to bisect since 5.4 when this issue was not there, but that's not at all trivial.

**Comment by lintujuh** [comment]
I tested your version on Win11 and for me it worked perfectly. I started the export of few images, switched to another virtual desktop, and the focus stayed on that desktop the whole export, and also remained there when the export had finished.

**Comment by Thanatomanic** [comment]
Okay, let me try to do the same on my Windows 11 laptop. Will probably only be able to do that later this week, but maybe I'll find time.

**Comment by Thanatomanic** [comment]
Perhaps you can ask other Windows testers on Pixls.us?

**Comment by Arecsu** [comment]
@lintujuh nice! could you please check if it also does not focus steal while minimized / at the bottom of other windows in the within the same workspace desktop? This way we see if we coincide with the report from @Thanatomanic 

And @Thanatomanic I think it is important to share the GTK libs and compiler used to build it. Good catch on that one. We don't have any logging paths in the code that would give us important data as far as I know.

Bisecting also won't be helpful as we know it's closely related to the event controllers or gtk4-compatible windowing system. I made an AI do some deep research on the GTK3 source code to see where and how it calls to Windows focus stealing APIs. We found a few, none of which were clearly used and triggered by the code at darktable. Ah, GTK3 and its quirks 🥲

I'll see if I could get a hold of a VM machine

**Comment by Thanatomanic** [comment]
I compile with GCC 16.2 in MSYS2 on Windows 10. Here are my packages:

<details>
<summary>My packages and details.</summary>

```
base 2022.06-1
base-devel 2026.08-3
cmake 4.4.2-1
diffutils 3.12-1
flex 2.6.4-4
gdb 17.1-3
git 2.55.0-1
intltool 0.51.0-4
make 4.4.1-3
mingw-w64-ucrt-x86_64-SDL2 2.32.10-1
mingw-w64-ucrt-x86_64-boost 1.91.0-3
mingw-w64-ucrt-x86_64-cfitsio 1~4.7.0-1
mingw-w64-ucrt-x86_64-cmake 4.4.2-2
mingw-w64-ucrt-x86_64-drmingw 0.9.11-2
mingw-w64-ucrt-x86_64-eigen3 5.0.1-1
mingw-w64-ucrt-x86_64-exiv2 0.28.8-1
mingw-w64-ucrt-x86_64-gcc 16.2.0-3
mingw-w64-ucrt-x86_64-gettext-tools 1.0-1
mingw-w64-ucrt-x86_64-gmic 3.7.0-2
mingw-w64-ucrt-x86_64-graphicsmagick 1.3.48-1
mingw-w64-ucrt-x86_64-gsl 2.8-1
mingw-w64-ucrt-x86_64-gtk3 3.24.52-1
mingw-w64-ucrt-x86_64-gtkmm3 3.24.10-3
mingw-w64-ucrt-x86_64-icu 78.3-4
mingw-w64-ucrt-x86_64-imath 3.2.3-1
mingw-w64-ucrt-x86_64-iso-codes 4.20.1-1
mingw-w64-ucrt-x86_64-lcms2 2.19.1-1
mingw-w64-ucrt-x86_64-lensfun 0.3.4-8
mingw-w64-ucrt-x86_64-libavif 1.4.2-1
mingw-w64-ucrt-x86_64-libgphoto2 2.5.34-2
mingw-w64-ucrt-x86_64-libheif 1.23.1-3
mingw-w64-ucrt-x86_64-libiptcdata 1.0.5-1
mingw-w64-ucrt-x86_64-libjpeg-turbo 3.2.0-1
mingw-w64-ucrt-x86_64-libjxl 0.12.0-1
mingw-w64-ucrt-x86_64-libpng 1.6.58-1
mingw-w64-ucrt-x86_64-libraw 0.22.2-1
mingw-w64-ucrt-x86_64-librsvg 2.62.3-1
mingw-w64-ucrt-x86_64-libsecret 0.21.7-1
mingw-w64-ucrt-x86_64-libtiff 4.7.2-1
mingw-w64-ucrt-x86_64-libwebp 1.6.0-1
mingw-w64-ucrt-x86_64-libxml2 2.15.3-1
mingw-w64-ucrt-x86_64-libxslt 1.1.45-1
mingw-w64-ucrt-x86_64-lua 5.5.1-1
mingw-w64-ucrt-x86_64-mimalloc 3.4.4-1
mingw-w64-ucrt-x86_64-ninja 1.13.2-1
mingw-w64-ucrt-x86_64-opencolorio 2.5.2-1
mingw-w64-ucrt-x86_64-openexr 3.4.14-1
mingw-w64-ucrt-x86_64-openjpeg2 2.5.4-2
mingw-w64-ucrt-x86_64-osm-gps-map 1.2.0-6
mingw-w64-ucrt-x86_64-portmidi 1~2.0.8-1
mingw-w64-ucrt-x86_64-potrace 1.16-3
mingw-w64-ucrt-x86_64-pugixml 1.16-1
mingw-w64-ucrt-x86_64-python-jsonschema 4.26.0-2
mingw-w64-ucrt-x86_64-qt5-svg 5.15.19+kde+r5-1
mingw-w64-ucrt-x86_64-qt5-tools 5.15.19-1
mingw-w64-ucrt-x86_64-qt5-winextras 5.15.19-1
mingw-w64-ucrt-x86_64-qtwebkit 5.212.0alpha4-27
mingw-w64-ucrt-x86_64-sqlite3 3.53.4-1
mingw-w64-ucrt-x86_64-webp-pixbuf-loader 0.2.7-2
ninja 1.13.2-1
pactoys r65.b5fcc0f-1
po4a 0.74-1
python-pip 26.2.1-1
zip 3.0-5
```
</details>

**Comment by Thanatomanic** [comment]
I managed to get build done on Windows 11 sooner than expected and I have some interesting news. I cannot get any focus stealing in Windows 11. I am not able to reproduce the report in #21829 for Windows 11. One specific thing I noticed is that on Windows 11 there exists a mechanism that the icon in the taskbar will flash up, like a notification. This happens each time a new image is exported, but I don't get focus stealing from other apps.
This flashing does not happen on 5.4.x, and on Windows 10 this was the last version that version that did not steal focus. So something definitely changed there, having different effects on different OSes.

**Windows 11**
- darktable 5.4.x -- no focus stealing, no flashing
- darktable 5.6.x -- no focus stealing, flashing on each exported file
- darktable master (https://github.com/darktable-org/darktable/commit/08217c239ef69c0eee0584bdc390a440fcb12b26) -- same as 5.6.x

**Windows 10**
- darktable 5.4.x -- no focus stealing
- darktable 5.6.x onwards, including this PR -- focus stealing

**Comment by lintujuh** [comment]
No focus stealing when minimized.

Now that @Thanatomanic pointed it out, I also noticed the flashing of the dt icon on the taskbar.

**Comment by Arecsu** [comment]
I've been debugging this all day. I had to install Windows in a VM otherwise it was pretty much impossible.

Findings: GTK4/last GTK3 libraries trigger some events to Windows that were not there before (plus our new changes). 

When an image or multiple images are exported, there is a toast "exporting [DIR/FILE] 2/7 etc" at the bottom/top of Darktable window. That toast changes, and THAT is what triggers the window attention in the taskbar. Windows seems to track "changes to a window" and signal a flash in the taskbar icon when apps do that. This toast for some reason qualifies to "change to the window of darktable". Maybe there is a proper way to make Darktable not doing that cleanly. I have yet to found a way to do it without deep changes to the code.

Regarding Windows 10 with stealing focus: it might be related to this as well, or it might be (also) a bug in older GTK libraries with Windows 10. I'm testing this under Windows 11, and it is proven to be quite the challenge. I've spent more than 2 hours debugging just that 🥲

I have a couple of things I'm trying, specifically for Windows, which is on window minimized/out of focus: hide the toast. And make the toast visible when window is focused. At least that's the only one that seems to be effective.

EDIT: hiding the toast makes no difference to the taskbar flashing unfortunately. Maybe the problem is the export dialog at the left sidebar at the bottom, too

**Comment by Arecsu** [comment]
Done. It wasn't about hiding the toast (directly). It was about avoid `dt_control_log()` to be triggered. This results in the toast not showing up on Windows, but focus and taskbar should not blink for each image exported.

Taskbar should only blink after the whole batch of images exported has finished. This is intended, at least judging from the code at `dt_ui_notify_user()`

I could not find a proper way without messing the code further to make `dt_control_log()` to show the toast BUT keeping it from stealing focus/taskbar light. So, it stays as a workaround for Windows. Rest of operative systems should keep working as intended.

If for some reason focus keeps being stolen, `dt_ui_notify_user()` should be suppressed for Windows, but I don't think that should be needed. At least, in Windows 11 it all works good.

@TurboGit this should be ready to be merged, finally

**Comment by Thanatomanic** [comment]
@Arecsu Thank you for the digging. I can confirm that this solves the focus stealing on export!

(P.S. And not to spoil the fun, but as I mentioned here https://github.com/darktable-org/darktable/issues/21829#issuecomment-5331231979 the same thing happens on import. I suppose there are other places where a toast appears. Some future work needed, I guess?)

**Comment by Arecsu** [comment]
Ah almost forgot about those. Yes, it is the exact same thing, imports and there is one or two places more where this happens. A proper toast fix is at least unachievable on my end, but a quick workaround to disable those in Windows should look really similar to this one.

The important thing here is: are you talking about purely focus stealing then, no problem with the taskbar lighting up, right? And also, focus stealing happens at the end of import, or with each image getting imported?

**Comment by Arecsu** [comment]
@Thanatomanic test them now with these last changes, it should be gone from import as well :)

**Comment by Thanatomanic** [comment]
Unfortunately, that did not resolve the focus stealing ~upon~ during import. ~I'll make a separate issue for that and make a screencast.~ Edit: I think that what I'm seeing is very similar to what I reference below. It's the 'working...' text that appears on the thumbnail that seems to cause the steal.

The import problem is much less annoying, because I typically stay in darktable while it's doing its work.

**Comment by Thanatomanic** [comment]
Actually, it might be the same as what happens here: #20442 and shown in this screencast https://github.com/darktable-org/darktable/issues/20442#issuecomment-5289671225

**Comment by TurboGit** [comment]
For the record, the windows build is failing with:

```
D:/a/darktable/darktable/src/src/imageio/storage/piwigo.c: In function 'store':
D:/a/darktable/darktable/src/src/imageio/storage/piwigo.c:1296:8: error: variable 'skipped' set but not used [-Werror=unused-but-set-variable=]
 1296 |   gint skipped = 0;
      |        ^~~~~~~
compilation terminated due to -Wfatal-errors.
cc1.exe: all warnings being treated as errors
```

**Comment by Arecsu** [comment]
I'll try to finalize this PR upcoming weekend hopefully with the import photos workaround working as well 👌

**Comment by radialmonster** [comment]
@Arecsu FYI, I think I found the underlying Windows cause (#20442, fix in #22243). Since #20054, `dt_colorspaces_set_display_profile()` calls `gdk_win32_window_get_handle()` on the center widget, which makes GDK convert the center view into a native child window. GtkOverlay re-shows, and so raises, its children on every size allocation, and GDK's Win32 raise calls `SetForegroundWindow()`. So the log and toast messages in `center_base` coming and going pull darktable to the front.

With the one-line fix, a 225-image export with another window in front no longer steals focus here (without it: 15 and 2 steals in two runs; with it: 0 and 0). So the Windows-only message suppression in this PR may no longer be needed, though the GTK-thread changes are a separate question. Happy to test anything.

**Comment by Thanatomanic** [comment]
Thanks @radialmonster !

It's quite curious to see that the focus stealing was already reported as one of two problems introduced in #20054 and the PR was merged regardless.

**Comment by wpferguson** [comment]
> It's quite curious to see that the focus stealing was already reported as one of two problems introduced in https://github.com/darktable-org/darktable/pull/20054 and the PR was merged regardless.

Because we missed it,  I actually remember seeing the screenshot when I pulled up the PR, but I didn't scroll back up and read it.  Lately our workload has increased 10 fold, but our manpower hasn't.

**Comment by radialmonster** [comment]
#21843 asked for Windows testers, so I built this branch (head a253a6b8) on Windows 11 and gave it a run. With an export of 225 images and another window in front, this branch had **no focus steals**, where its own merge base had 15 and 2 in two runs. The export case in #21829 is fixed here.

I did some of the mechanical work in case it saves you time.

**Rebased onto current master:** https://github.com/radialmonster/darktable/tree/agent/21949-rebased — your "gui: keep background job widgets on the GTK thread" commit, unchanged and with your authorship, applied to master `5af33dc02d`. It builds on Windows (MSYS2 UCRT64) and I ran a 225-image export against it: the background-jobs panel updated normally and nothing crashed. Take it, or ignore it, as you prefer.

I left the two `#ifndef _WIN32` commits out of that branch for two reasons:

1. They are what conflicts with master. The conflicts are in `disk.c`, `email.c`, `gallery.c` and `latex.c`, from four commits since your base: 64b4e2b4b2, c78be1835b, b57912c25b and 9a334c1969 (#22143). (64b4e2b4b2 only moved the *console* print to `DT_DEBUG_IMAGEIO`; the on-screen per-image message is still in master.)
2. They are also what the Windows job is failing on:

```text
piwigo.c:1296:8: error: variable 'skipped' set but not used [-Werror=unused-but-set-variable=]
```

With the `dt_control_log()` block under `#ifndef _WIN32`, `skipped` is still assigned at line 1411 but no longer read on Windows, and the build uses `-Werror`. If you keep those commits, `(void)skipped;` under `#ifdef _WIN32` clears it, and a single helper that is a no-op on Windows would avoid the `#ifdef`s spreading across the storage modules.

On how this sits next to #22243: the two fit together — #22243 removes the cause, so this PR can keep its background-jobs GTK-thread fix without needing the Windows message suppression, and Windows keeps the progress messages. #22243 stops the center view from being turned into a native child window, which is what lets GDK raise it with `SetForegroundWindow()`. With it, the same 225-image export shows 0 steals here **with the progress messages still displayed**, so Windows users would keep the export and import feedback. On this branch that window is still created, and the other triggers still reproduce for me (thumbnail hover, Alt+Tab with the pointer on a thumbnail, and the OpenCL messages at startup).

Your background-jobs refactor is separate from all of that and #22243 does not touch it.

Happy to re-test any version on Windows; I have the builds and an automated probe set up.
