### ISSUE TITLE
current master fails to build

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#17586]
### Describe the bug

I cannot build current master

### Steps to reproduce

try to build current master

### Expected behavior

dt should build fine as usual

### Logfile | Screenshot | Screencast

I get such error

```
[ 56%] Building C object bin/CMakeFiles/lib_darktable.dir/lua/widget/stack.c.o
[ 56%] Building C object bin/CMakeFiles/lib_darktable.dir/lua/widget/widget.c.o
[ 57%] Building C object bin/CMakeFiles/lib_darktable.dir/lua/widget/text_view.c.o
[ 57%] Building C object bin/CMakeFiles/lib_darktable.dir/common/cups_print.c.o
[ 57%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printing.c.o
[ 57%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printprof.c.o
[ 57%] Built target darktable-rs-identify
Merging translations into /home/gerber/.local/git/darktable/build/share/darktable/org.darktable.darktable.desktop.
[ 57%] Checking validity of org.darktable.darktable.desktop
[ 57%] Built target validate_darktable_desktop
[ 57%] Built target darktable.desktop_file
Merging translations into /home/gerber/.local/git/darktable/build/bin/../share/metainfo/org.darktable.darktable.appdata.xml.
CREATED /home/gerber/.local/git/darktable/build/bin/../share/metainfo/org.darktable.darktable.appdata.xml
[ 57%] Built target darktable.appdata_file
[ 57%] Built target validate_noiseprofiles_json
/home/gerber/.local/git/darktable/src/imageio/imageio.c:239:38: error: 'dt_imageio_open_exr' undeclared here (not in a function); did you mean 'dt_imageio_open_ldr'?
  239 |   { DT_FILETYPE_OPENEXR, TRUE, 0, 4, dt_imageio_open_exr,
      |                                      ^~~~~~~~~~~~~~~~~~~
      |                                      dt_imageio_open_ldr
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2014: bin/CMakeFiles/lib_darktable.dir/imageio/imageio.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2527: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 57%] Built target validate_wbpresets_json
make: *** [Makefile:156: all] Error 2

```

the full report is here: https://bpa.st/XTPUU

git bisect gives me:
```

e38d2c8db4f457a0e45624d646244446352de609 is the first bad commit
commit e38d2c8db4f457a0e45624d646244446352de609 (HEAD)
Author: Ralf Brown <ralfbrown@users.noreply.github.com>
Date:   Thu Aug 22 17:29:15 2024 -0400

    add more magic bytes, use only appropriate loader when magic matches

 src/common/image.h    |  11 +--
 src/imageio/imageio.c | 527 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 2 files changed, 422 insertions(+), 116 deletions(-)
```

@ralfbrown may I ping you here!?

### Commit

e38d2c8db4f457a0e45624d646244446352de609

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+632~ge0b2e1f0fc

### What OS are you using?

Linux

### What is the version of your OS?

gentoo

### Describe your system?

* OS                : Linux - kernel 6.10.10-gentoo
* Distro            : Gentoo Base System release 2.15
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-550.107.02-r1
* OpenCL installed  : Yes (opencl-headers-2023.12.14)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.13-r1
* Desktop           : KDE 6
* GTK+              : gtk+-3.24.41-r1
* gcc               : 13.3.1_p20240614
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

see above

**Comment by AxelG-DE** [comment]
actually this one is a rather old commit, plus openexr is disabled on my end

my openexr version is: media-libs/openexr-3.2.4-r2

**Comment by AxelG-DE** [comment]
$ cat BISECT_LOG 
```
git bisect start
# Status: warte auf guten und schlechten Commit
# bad: [63cf4e6d9be859d84fbdb1dbf42d14bfb75ca2bb] Merge pull request #16658 from jenshannoschwalm/clang_errors_2
git bisect bad 63cf4e6d9be859d84fbdb1dbf42d14bfb75ca2bb
# Status: warte auf gute(n) Commit(s), schlechter Commit bekannt
# bad: [63cf4e6d9be859d84fbdb1dbf42d14bfb75ca2bb] Merge pull request #16658 from jenshannoschwalm/clang_errors_2
git bisect bad 63cf4e6d9be859d84fbdb1dbf42d14bfb75ca2bb
# Status: warte auf gute(n) Commit(s), schlechter Commit bekannt
# good: [587c6d97d88e04e5a16def845efcad79627d663a] Update relnotes for new LibRaw supported cams
git bisect good 587c6d97d88e04e5a16def845efcad79627d663a
# bad: [d83cbc298e03d0465429ef37b91397df8c698a99] Rework Color equalizer picker
git bisect bad d83cbc298e03d0465429ef37b91397df8c698a99
# bad: [fe3c6b3918d46186d1348204468a1170514e420a] [CI/nightly]: bump xcode for macos-14 runner
git bisect bad fe3c6b3918d46186d1348204468a1170514e420a
# bad: [decff89943798a9223f8d077ab848d3e93c52b62] Merge pull request #16543 from jenshannoschwalm/color_equalizer_picker
git bisect bad decff89943798a9223f8d077ab848d3e93c52b62
# bad: [928f08d3fdbdb2a95bcb61fd2c5591b30f962fe8] imageio_libraw: add Canon EOS Ra support
git bisect bad 928f08d3fdbdb2a95bcb61fd2c5591b30f962fe8
# bad: [9c761ab164dbec9e8959e0647f96ccf40f8abe65] Better approximation of the picker coordinates
git bisect bad 9c761ab164dbec9e8959e0647f96ccf40f8abe65
# bad: [e218b77121773df7d93b6a5022f25e2014fb7fdf] Refactor some picker functions
git bisect bad e218b77121773df7d93b6a5022f25e2014fb7fdf
# bad: [e2042d91ece193e009d5837648038191e8986c75] Make pickers position relative to image input
git bisect bad e2042d91ece193e009d5837648038191e8986c75
# first bad commit: [e2042d91ece193e009d5837648038191e8986c75] Make pickers position relative to image input
# bad: [2274c2a22197fe38d94a4386a39caae503665dbf] Merge pull request #17568 from darktable-org/po/filmstrip-sel
git bisect bad 2274c2a22197fe38d94a4386a39caae503665dbf
# good: [94ed1009a629c5b8f16ca0fc2d6d7e9bc3bf2c85] bugfix for zooming in thumbtable-filemanager
git bisect good 94ed1009a629c5b8f16ca0fc2d6d7e9bc3bf2c85
# good: [f737cc4fdd277d82fb2a881283900c412726be65] Merge pull request #17558 from zisoft/macos-open-url
git bisect good f737cc4fdd277d82fb2a881283900c412726be65
# bad: [b8db09c52028054740efa33f7350107d6dd70fa1] Updates to pt_BR
git bisect bad b8db09c52028054740efa33f7350107d6dd70fa1
# good: [e0b2e1f0fcbd2b4a6e2e5f68357646c36211277a] src/common/image.c: Avoid a crash when cache is not yet initialized.
git bisect good e0b2e1f0fcbd2b4a6e2e5f68357646c36211277a
# bad: [0a6cc9404802b2fb3b75583160441778ace60889] fix crash on SECOND entry to darkroom with unsupported image
git bisect bad 0a6cc9404802b2fb3b75583160441778ace60889
# bad: [3fb947c287f184f547e0e410a3ca36b15f59a1c4] id RAW formats which have TIFF signature by looking for manufacturer name
git bisect bad 3fb947c287f184f547e0e410a3ca36b15f59a1c4
# bad: [0883f4e3917dfad09644946a435de502b28035be] remove obsolete code
git bisect bad 0883f4e3917dfad09644946a435de502b28035be
# bad: [e38d2c8db4f457a0e45624d646244446352de609] add more magic bytes, use only appropriate loader when magic matches
git bisect bad e38d2c8db4f457a0e45624d646244446352de609
# first bad commit: [e38d2c8db4f457a0e45624d646244446352de609] add more magic bytes, use only appropriate loader when magic matches
```

**Comment by AxelG-DE** [comment]
@kmilos I have had just pulled and hence was on a fresh master and checked open issues, but yes, not the open PRs. 

I consider it fixed, once it is merged, BTW :)

**Comment by AxelG-DE** [comment]
https://github.com/darktable-org/darktable/pull/17584 got merged. Closing
