### ISSUE TITLE
Can't compile Darktable anymore with GCC or CLang

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#21911]
Can't compile Darktable anymore with GCC or CLang on GNU/Debian.

```
[ 59%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/colorpicker.dir/colorpicker.c.o
/usr/bin/x86_64-linux-gnu-ld.bfd: libdarktable.so: undefined reference to `Imf_3_4::Chromaticities::Chromaticities(Imath_3_2::Vec2<float> const&, Imath_3_2::Vec2<float> const&, Imath_3_2::Vec2<float> const&, Imath_3_2::Vec2<float> const&)'
[ 59%] Linking C shared module libexport.so
clang-21: error: linker command failed with exit code 1 (use -v to see invocation)
```

I get the same error with GCC, this rules out a compiler bug so maybe a GNU/linker bug.

That's the first time I'm blocked with Darktable meaning **I'll suspend the integration for now until this is solved**.

Also, looking for feedback to understand if someone else has the same issue? And a way to work around?

**Comment by wpferguson** [comment]
I can compile on Ubuntu 22.04, GCC 12.3.0 5.7.0+547~g9ef2601ae9

EDIT:

I can build on 26.04, GCC 15.2.0 with an out of date system.  I'll update to the current packages and try again.

EDIT 2:

Updated the system packages then built cleanly again.

EDIT 3:

The 26.04 builds did not include opencl.

**Comment by gi-man** [comment]
I looked thru OBS master and it's being failing since 5 days on all OS. Seems to not be related to this issue. This is the last successful commit: https://github.com/darktable-org/darktable/commit/fab54504284fccd590f4e68938c4c7b55f3b5544 

The CI nightly are compiling.

I was able to compile master and run on Fedora 44 KDE.

**Comment by TurboGit** [comment]
My system is GNU/Debian/sid.

- gcc (Debian 16.2.0-1) 16.2.0

- clang-21

- GNU ld (GNU Binutils for Debian) 2.47

**Comment by TurboGit** [comment]
@gi-man : I have the same issue when trying to compile https://github.com/darktable-org/darktable/commit/fab54504284fccd590f4e68938c4c7b55f3b5544. Also as I'm compiling everything before pushing I'm pretty sure that current master was compiling without issue some days ago. So this means there was an update on my system that broke Darktable. So sure what actually for the moment.

**Comment by TurboGit** [comment]
On my apt log I have:

```
Start-Date: 2026-08-18  09:33:35
Commandline: apt upgrade
Install: libimath-3-2-30:amd64 (3.2.2-2, automatic)
```

And given the issue above looks like the culprit. I also found out that I can compile without OpenEXR. So probably that `libimath` has been upgraded and `libopenexr` not yet built on top of it. That's a packaging issue, I'll have to wait for Debian to propose a new libopenexr but at least I have a workaround.

**Comment by da-phil** [comment]
> I looked thru OBS master and it's being failing since 5 days on all OS. Seems to not be related to this issue. This is the last successful commit: [fab5450](https://github.com/darktable-org/darktable/commit/fab54504284fccd590f4e68938c4c7b55f3b5544)
> 
> The CI nightly are compiling.
> 
> I was able to compile master and run on Fedora 44 KDE.

Yeah, those are unrelated issues, one was related to how OBS was linking darktable, this was already fixed in https://github.com/darktable-org/darktable/pull/21865.

However, introducing a new binary (darktable-mcp), caused another unrelated failure for RPM based builds, which I fixed in this OBS change request: https://build.opensuse.org/request/show/1371329

And those are the other two (unresolved) issues which break some OBS builds:
* GCC 16.2.0 segfaults compiling the new contrastntexture module on Debian Unstable
* Fedora Rawhide's own repository is broken

**Comment by yuri1969** [comment]
>     * GCC 16.2.0 segfaults compiling the new contrastntexture module on Debian Unstable

Linking to #21801

**Comment by Donatzsky** [comment]
> GCC 16.2.0 segfaults compiling the new contrastntexture module on Debian Unstable

When talking about this on the Arch Linux IRC, it was determined to likely be due to `makepkg` enabling -O2. Disabling optimisations should work around it for now.

**Comment by Donatzsky** [comment]
> GCC 16.2.0 segfaults compiling the new contrastntexture module on Debian Unstable

Update on this here: https://github.com/darktable-org/darktable/issues/21801#issuecomment-5380506263

**Comment by TurboGit** [comment]
FYI: Fixed in GNU/Debian with just pushed `libopenexr-3-4-33`.
