### ISSUE TITLE
compilation problem fedora 34

### ISSUE THREAD

**Issue by meplan** [darktable-org/darktable#8937]
**Describe the bug/issue**
I know that compilation should be done with gcc-10 or clang-11 but after updating my system gcc is updated to v11 and clang to v12. So here is the list of my pbs:
1. LLVM is not detected while llvm-devel-12/libs/static/... are installed
2. compilation abort with 
     a.) gcc-11:
          in file src/iop/channelmixerrgb.c:2249:5:
          src/common/iop_profile.h:371:3: error: ‘dt_Lab_to_XYZ’ accessing 16 bytes in a region of size 12 [-Werror=stringop-overflow=]
         371 |   dt_Lab_to_XYZ(lab, xyz);

    b.)clang-12:
        darktable/src/common/box_filters.c:1293:1: fatal error: loop not vectorized: the optimizer was unable to perform the 
        requested transformation; the transformation might be disabled or specified as part of an unsupported transformation
        ordering [-Wpass-failed=transform-warning]
       #pragma omp simd aligned(x) reduction(max : m)

Thank you for your help
Olivier

**Platform**
* darktable version : git master branch
* OS                :  Linux -kernel-5.11.18-300
* Linux - Distro    : fedora 34

**Comment by aurelienpierre** [comment]
Fixed in fc4374280a6795cfc3b5db993d4dea37cb2ac3db
