### PR TITLE
Fix build with libavif 0.11.1 and older

### LINKED ISSUE #17182: git master : commit 2da359d : compile error : Debian stable
### Describe the bug

Make fails after commit https://github.com/darktable-org/darktable/commit/2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b.

### Steps to reproduce

Build darktable git master:
```
git clone https://github.com/darktable-org/darktable.git
cd darktable
git submodule update --init
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/usr/source/darktable/install -DCMAKE_BUILD_TYPE=Release ..
make 
```
I get this error:
```
...
[ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/home/magnus/usr/source/darktable/src/imageio/imageio_avif.c:113:10: error: void value not ignored as it ought to be
  113 |   result = avifRGBImageAllocatePixels(&rgb);
      |          ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2238: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2494: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

### Expected behavior

Darktable should build. The commit up to and including https://github.com/darktable-org/darktable/commit/517889efe01b9626a82e98021df670d7c5bf7c94 was fine

### Logfile | Screenshot | Screencast

_No response_

### Commit

https://github.com/darktable-org/darktable/comm2da359d5b683eb0f9ab8a280a0626e9ec53e9e9bit/ beaks build.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

release-4.9.0-73-g2da359d5b6, built from source

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable bookworm 12.6.

### Describe your system?

- OS : Linux debian 6.1.0-23-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
- Linux - Distro : Debian 12.6 Stable Bookworm
- Memory : 64 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : NVIDIA 535.183.01 from Debian non-free repo
- OpenCL installed : Yes,   OpenCL 3.0 CUDA 12.2.148
- OpenCL activated : Yes (but --disable-opencl does not help, same issue)
- Xorg : X11
- Desktop : Gnome 43.9
- GTK:  3.24.38-2~deb12u1, 4.8.3+ds-2+deb12u1, 2.24.33-2
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release
- Intel® Core™ i9-14900K × 32
- motherboard: ASUS PRIME Z790-A WIFI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000], NVIDIA 535.183.01 from Debian non-free repo

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by victoryforce**
Resolves #17182.

### CODE REVIEW

**Comment by wpferguson** [comment]
Doesn't work on Ubuntu 22.04 with libavif 0.9.3-3

**Comment by jenshannoschwalm** [comment]
> CI seems pretty much useless when all checks pass and the software wont even build.

At least CI made me aware of some functions returning error conditions that should be checkedwhile processing :-)

**Comment by wpferguson** [comment]
Compiles on 22.04 with libavif 0.9.3-3

**Comment by KarlMagnusLarsson** [comment]
Compiles and runs on Debian 12.6 with libavif-dev/stable,now 0.11.1-1 amd64 [installed].

I have also tested with some actual avif picture files, for the first time ever. Works fine in lighttable and darkroom. The import function could not generate a preview, though. All I got was a darktable icon.

**Comment by victoryforce** [comment]
> The import function could not generate a preview, though. All I got was a darktable icon.

It should not be so if the image is not corrupted. Please run darktable with the `-d imageio` debug channel.

**Comment by KarlMagnusLarsson** [comment]
> > The import function could not generate a preview, though. All I got was a darktable icon.
> 
> It should not be so if the image is not corrupted. Please run darktable with the `-d imageio` debug channel.

Starting dt and importing two AVIF files and then going back and forth between lighttable and darkroom looks like this. The files display both in lighttable and darkroom.
```
./darktable  -d imageio --configdir /home/magnus/test/darktable-test/config --cachedir /home/magnus/test/darktable-test/cache
darktable 4.9.0+74~gfc00a6f2a2
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

    31,8504 [dt_imageio_export_with_flags]  modules: colorin colorout gamma
    31,8505 [dt_imageio_export] thumbnail imgid 1, 1204x800 --> 677x450 (scale=0,5625, maxscale=1,0000). upscale=no, hq=no
    31,8540 [dt_imageio_export_with_flags]  modules: colorin colorout gamma
    31,8540 [dt_imageio_export] thumbnail imgid 2, 1204x800 --> 677x450 (scale=0,5625, maxscale=1,0000). upscale=no, hq=no
    53,2524 [dt_imageio_export_with_flags]  modules: colorin colorout gamma
    53,2524 [dt_imageio_export] thumbnail imgid 1, 1204x800 --> 677x450 (scale=0,5625, maxscale=1,0000). upscale=no, hq=no
    55,2235 [dt_imageio_export_with_flags]  modules: colorin colorout gamma
    55,2235 [dt_imageio_export] thumbnail imgid 2, 1204x800 --> 677x450 (scale=0,5625, maxscale=1,0000). upscale=no, hq=no
```

The import preview looks like this.
Screenshot from 2024-07-25 19-25-51

I used files from here: https://github.com/link-u/avif-sample-images, fir instance this one: https://github.com/link-u/avif-sample-images/blob/master/fox.profile0.8bpc.yuv420.avif

If this is an issue or not, that I do no know, but I propose to deal with that separately, if needed. Whatever this is, it is not related to your PR at all. This is the same in release-4.8.0 code.
