### PR TITLE
maintenance: move copy_pixel_nontemporal to imageop.h

### PR DESCRIPTION
**Pull request by ralfbrown**
Move the definition from darktable.h to imageop.h to reduce the number of files which need to compile the SSE header.  Add a wrapper around _mm_sfence that falls back to a standard C11 function when compiling without SSE, and add calls to it to graduatednd.c.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by MStraeten** [comment]
breaks build on macOS arm64 (apple arm64 doesn't support SSE):
```
In file included from /Users/martinstraeten/src/darktable/src/develop/develop.h:30:
/Users/martinstraeten/src/darktable/src/develop/imageop.h:601:8: fatal error: no type named '__c11_atomic_thread_fence' in namespace 'std'
  std::atomic_thread_fence(std::memory_order_seq_cst);
  ~~~~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/stdatomic.h:68:36: note: expanded from macro 'atomic_thread_fence'
#define atomic_thread_fence(order) __c11_atomic_thread_fence(order)
                                   ^
1 error generated.
```
git bisect:
```

bde24296dfb8e0d722a4caad35cc6f1591c23b7b is the first bad commit
commit bde24296dfb8e0d722a4caad35cc6f1591c23b7b
Author: Ralf Brown <ralfbrown@users.noreply.github.com>
Date:   Sun Feb 19 11:44:09 2023 -0500

    maintenance: move copy_pixel_nontemporal to imageop.h (#13673)

    * move copy_pixel_nontemporal to imageop.h

    Move the definition from darktable.h to imageop.h to reduce the number of files which
    need to compile the SSE header.  Add a wrapper around _mm_sfence that falls back to
    a standard C11 function when compiling without SSE, and add calls to it to graduatednd.c.

```

**Comment by ralfbrown** [comment]
Hmm.  Does that compiler need an additional flag or include to make it C++11 compliant?  Since the complaint is about the std:: version, it must be from one of the *.cc C++ files.

We could just zap the fence if you can give me a #define (or combination of them) to select just the macOS arm64.

**Comment by MStraeten** [comment]
I don't have programming experience sufficient to give any hint on this...
At least the code compiles fine with an intel mac using the same Xcode commandline version and sdk, so it seems to be arm64 specific

```
cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
```

**Comment by ralfbrown** [comment]
Can you try changing the line to
```
atomic_thread_fence(std::memory_order_seq_cst);
```
I just checked, and that builds successfully with GCC on Linux -- the C++ version of the line is because I originally got a compile failure because the parameter was undefined without the std:: prefix.

**Comment by MStraeten** [comment]
```
[ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/common/histogram.c.o
In file included from /Users/martinstraeten/src/darktable/src/common/exif.cc:38:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/array:114:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/algorithm:653:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/functional:500:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1756:1: fatal error: expected expression
atomic_is_lock_free(const shared_ptr<_Tp>*)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/stdatomic.h:73:73: note: expanded from macro 'atomic_is_lock_free'
#define atomic_is_lock_free(obj) __c11_atomic_is_lock_free(sizeof(*(obj)))
                                                                        ^
[ 37%] Building C object bin/CMakeFiles/lib_darktable.dir/common/image.c.o
[ 38%] Building C object bin/CMakeFiles/lib_darktable.dir/common/history_snapshot.c.o
[ 38%] Building C object bin/CMakeFiles/lib_darktable.dir/common/image_cache.c.o
[ 38%] Building C object bin/CMakeFiles/lib_darktable.dir/common/image_compression.c.o
1 error generated.
```

**Comment by ralfbrown** [comment]
OK, looks like we'll have to punt on the C++ when compiling for Apple arm64.  Does it compile successfully if you just comment out that line?

**Comment by MStraeten** [comment]
```
#ifdef __cplusplus
  // std::atomic_thread_fence(std::memory_order_seq_cst);
#else
  atomic_thread_fence(memory_order_seq_cst);
#6890 
```
results in 
```
In file included from /Users/martinstraeten/src/darktable/src/common/exif.cc:38:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/array:114:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/algorithm:653:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/functional:500:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1756:1: fatal error: expected expression
atomic_is_lock_free(const shared_ptr<_Tp>*)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/stdatomic.h:73:73: note: expanded from macro 'atomic_is_lock_free'
#define atomic_is_lock_free(obj) __c11_atomic_is_lock_free(sizeof(*(obj)))
                                                                        ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Error 1
make[1]: *** [bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ralfbrown** [comment]
The only thing I can think of now is that the compiler's stdatomic.h is broken when included inside an extern "C"{} block, which is what's happening for exif.cc.  Try commenting out that include (right above copy_pixel_temporal).

**Comment by parafin** [comment]
Yeah, including system headers inside extern "C" is very bad idea. Don't do that.

**Comment by parafin** [comment]
`extern "C"` should go into .h files (guarded with `#ifdef __cplusplus`), function/variable declarations should be put there. And we have them in .cc files, which is totally backwards and was destined to create this type of problems.

**Comment by parafin** [comment]
Regarding this PR itself - why are you using `std::atomic_thread_fence` for C++ if you include stdatomic.h for both C and C++? C atomic operations should work on C++, shouldn't they? Or if you want to use std:: version, you need to include the correct header, which of course will totally break when inside extern "C".

**Comment by parafin** [comment]
My suggestion is to revert this PR and deal with `extern "C"` mess first.

**Comment by ralfbrown** [comment]
I believe I've dealt with the `extern "C"` mess in #13696.

**Comment by MStraeten** [comment]
> The only thing I can think of now is that the compiler's stdatomic.h is broken when included inside an extern "C"{} block, which is what's happening for exif.cc. Try commenting out that include (right above copy_pixel_temporal).

commenting that out results in an succesful build
