### PR TITLE
[AI] Add TIFFTAG_PREVIEWCOLORSPACE fallback for libtiff < 4.6

### LINKED ISSUE #20932: imageio_dng.c error: ‘TIFFTAG_PREVIEWCOLORSPACE’ undeclared (first use in this function)
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

when compiling:
```
....
/home/a/darktable/src/imageio/imageio_dng.c: In function ‘_register_extra_dng_fields’:
/home/a/darktable/src/imageio/imageio_dng.c:82:7: error: ‘TIFFTAG_PREVIEWCOLORSPACE’ undeclared (first use in this function)
   82 |     { TIFFTAG_PREVIEWCOLORSPACE, 1, 1, TIFF_LONG, FIELD_CUSTOM,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~

```

### Steps to reproduce

 bash ../build.sh --prefix /opt/darktable --build-type Release --enable-ai

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

current master

### What OS are you using?

Linux

### What is the version of your OS?

debian 12

### PR DESCRIPTION
**Pull request by andriiryzhkov**
Fixes #20932

`imageio_dng.c` fails to compile on libtiff < 4.6 (Debian 12, Ubuntu 22.04 / 24.04) because `TIFFTAG_PREVIEWCOLORSPACE` was only added in libtiff 4.6.

Adds a one-line `#ifndef` fallback that defines the macro to its DNG-spec value (50970) when libtiff didn't.

Verified against libtiff 4.3.0 source – it's the only DNG tag darktable uses that's missing in pre-4.6; everything else (`DNGVERSION`, `COLORMATRIX1`, `BLACKLEVEL`, `ACTIVEAREA`, …) has been there since 4.0.

### CODE REVIEW

**Review by TurboGit — APPROVED** [review]
Thanks!

**Comment by da-phil** [comment]
It works for me now, thank you @andriiryzhkov!

```
  1749.0886 [neural_restore] raw preview: imgid=11078 bayer patch=(0.500,0.500) widget=752x556 filters=0x94949494
  1750.9975 [neural_restore] raw preview: full=5240x3912 ori=0x6 patch_center=(0.500,0.500) -> sensor=(2342,1580 556x752) bayer
  1752.4428 [neural_restore] raw preview: inference returned err=0 src=0x7354ced08010 denoised=0x7354cc5ee010 requested=556x752 actual=752x554
  1760.8006 [neural_restore] job started: task=raw denoise, scale=1, images=1
  1760.8233 [neural_restore] processing imgid 11078 -> /home/phil/Pictures/P8100765_raw-denoise.dng
  1760.8233 [neural_restore] imgid 11078: flags=0x643 channels=1 filters=0x94949494 (bayer)
  1760.8816 [restore_raw_bayer] 5240x3912 sensor (CFA origin 0,0), working 2620x1956 packed, tile T=2048, 2x1 grid (2 tiles)
  1760.8852 [restore_raw_bayer] raw CFA range [256.0, 3317.0], black=[255,256,255,255] white=4001 wb_coeffs=[520.000,256.000,470.000,0.000] wb_norm=[1.000,1.000,1.000]
  1760.9632 [restore_raw_bayer] tile0 model_input range R=[-0.000,0.340] G1=[0.001,0.731] G2=[0.001,0.730] B=[-0.000,0.454]
  1761.9251 [restore_raw_bayer] tile0 model_output range R=[0.001,0.385] G=[0.001,0.832] B=[0.000,0.520] in_mean=0.035 out_mean=-27841051.131 gain=-1.272e-09
  1762.9454 [restore_raw_bayer] cfa_out u16 range [258, 3707] mean=409 (DNG will advertise black~255 white=4001)
  1762.9651 [neural_restore] embedded JPEG preview from source 3200x2400 (1003750 bytes)
  1763.6364 [neural_restore] imported imgid=63606: /home/phil/Pictures/P8100765_raw-denoise.dng
```

**Comment by pehar1** [comment]
Works for me too now, with `5.5.0+1165~ged6e487df5`, Linux, Ubuntu 24.04 but getting warnings during build process
```
/media/ph/ssd-120/darktable/master/src/ai/backend_onnx.c:516:11: warning: ignoring return value of function declared with attribute ‘warn_unused_result’ [-Wunused-result]
  516 |           probe_api->ReleaseAvailableProviders(providers, n_providers);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/ph/ssd-120/darktable/master/src/ai/backend_onnx.c: In function ‘_ort_has_provider’:
/media/ph/ssd-120/darktable/master/src/ai/backend_onnx.c:878:5: warning: ignoring return value of function declared with attribute ‘warn_unused_result’ [-Wunused-result]
  878 |     g_ort->ReleaseAvailableProviders(providers, n);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
