### PR TITLE
Force screen pipe restarting on history changes which change image dimensions

### LINKED ISSUE #21185: History stack not applied on click / partially applied / module value changes dont lead to redraw sometimes
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

This started happening in one of the recent git versions. When clicking in the history stack the thumbnail always updates yet the main view only changes sometimes/partially. The same happens when changing e. g. exposure in the exposure value. You drag the slider somewhere, nothing happens, you move it again, it gets applied.

https://github.com/user-attachments/assets/1defd788-4caf-48df-8868-50d474a40780

Also happens without opencl

### Steps to reproduce

Click around the history stack,
sometimes it gets applied, sometimes it doesnt

or change exposure,
sometimes it gets applied, sometimes it doesnt

### Expected behavior

history stack should always get applied / Module parameters as well

### Logfile | Screenshot | Screencast

_No response_

### Commit

_No response_

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

sometimes it gets applied, sometimes it doesnt

### What OS are you using?

Linux

### What is the version of your OS?

Arch, latest

### Describe your system

_No response_

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RX 6700 XT

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

_No response_

### PR DESCRIPTION
**Pull request by piratenpanda**
fixes #21185 CC @jenshannoschwalm

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Thats all good to me. We missed the restart to finalize dimensions also for the screen pipes.

As described in the issue, especially make sure you have history entries changing dimension like crop/rotate/lens...

**Comment by victoryforce** [comment]
@jenshannoschwalm The red CI here is due to the following error in non-Linux builds:

```
/Users/runner/work/darktable/darktable/src/src/common/opencl.c:2955:12: fatal error: unused variable 'preheated' [-Wunused-variable]
 2955 |   gboolean preheated = FALSE;
      |            ^~~~~~~~~
1 error generated.
```

caused by commit 9e36df03444e254f5e19799444ad7265e0760661

Here "`gboolean preheated = FALSE;`" should also be wrapped in "`#if defined(__linux__)`"

**Comment by jenshannoschwalm** [comment]
Im on phone, can you fix this for me? (Dont worry about the preheating)

**Comment by jenshannoschwalm** [comment]
@TurboGit could you enlighten me why the CI build still fails with the error regarding the "preheating" even if that got reverted? Just pinging as this PR indeed is a bug fix.

**Comment by TurboGit** [comment]
> @TurboGit could you enlighten me why the CI build still fails with the error regarding the "preheating" even if that got reverted? Just pinging as this PR indeed is a bug fix.

Because the PR here has not been rebased on top of the revert.

**Comment by jenshannoschwalm** [comment]
@piratenpanda sorry for the mess, you have to rebase on current master and force-push.

**Comment by piratenpanda** [comment]
A new one was faster where I am currently. See https://github.com/darktable-org/darktable/pull/21207
