### ISSUE TITLE
CSS `font-size` parameter hyper-sensitive upgrading from 3.0.0 to 3.0.1/3.0.2

### ISSUE THREAD

**Issue by Rmano** [darktable-org/darktable#4769]
**Describe the bug**

When trying to adjust the basic font size of the interface, editing `/usr/share/darktable/themes/darktable.css`, changing the value from the default 1em to 0.9em or 1.1em creates very big changes in font size (see the screenshots). It worked perfectly in 3.0.0.  (**corrected, it was 3.0.1 in the first version**)

**To Reproduce**

1. Edit  /usr/share/darktable/themes/darktable.css and around line 160 change the value of `font-size:` from `1em` to something like `0.9em` or `1.1em`.
2. Launch `darktable`

**Expected behavior**

A change of 10% of that parameter should be reflected as a change of (around) 10% of the font size in the main interface. 
It worked that way on 3.0.0

**Screenshots**

Here I made two screenshots with two values of `font-size:`

![2020-04-18_22-35](https://user-images.githubusercontent.com/6414907/79683117-0d337400-8228-11ea-9591-f745f973925d.png)

![2020-04-18_22-36](https://user-images.githubusercontent.com/6414907/79683119-0efd3780-8228-11ea-8460-d33bf7c2b720.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2, installed by PPA https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/darktable
 - OS: Ubuntu 18.04
 - No OpenCL
 - Internal Intel graphic card

**Additional context**

I can use a workaround changing the DPI of the monitor (although it shouldn't be needed; in 3.0.1 the automatic detection worked fine.)

BTW, thank you again for this great SW

**Comment by Nilvus** [comment]
But nothing has changed on darktable for this part between 3.0.1 and 3.0.2. And em means emphasize about your OS font size, so it's probably more on your OS setting sizes. Or related to the PPA you are using. We already see reports on forums of bugs not related to darktable but to this PPA.

**Comment by Nilvus** [comment]
Finally just tested your PPA, 3.0.2 compiled and the master. I confirm this issue. Anyway it's not CSS related. CSS only text, that something else that has changed. Don't understand what. @aurelienpierre, @AlicVB: any idea on this?

**Comment by Rmano** [comment]
I tried to install it in another PC, and I have the same problem. Somewhere, where this number is used, must have changed something...

**Comment by Rmano** [comment]
This is a clear candidate for a `git bisect` exercise. I'll see if I can put it on this weekend. Thanks @Nilvus for taking the time to confirm it...

**Comment by Nilvus** [comment]
> This is a clear candidate for a `git bisect` exercise. I'll see if I can put it on this weekend. Thanks @Nilvus for taking the time to confirm it...

I've just tested 3.0.0 release and that was ok on this release. But I have same issue with 3.0.1, so the issue doesn't appear between 3.0.1 and 3.0.2 but between 3.0.0 and 3.0.1.

**Comment by Rmano** [comment]
Yep. I had no time to check it, just scrolled rapidly through the commits... the only commit I found that touches something there is 1b28b36, but I do not think it has anything to do... I am swamped by on-line class and exams (prof side, but swamped I am ;-))  and never built DT, I hope to have time this weekend...

**Comment by Nilvus** [comment]
@Mark-64: what do you think of that. Is your work on HiDPI for Windows could cause that issue. It appears between 3.0.0 and 3.0.1. The commit pointed by @Rmano is your commit and on what I just checked on merged PR for 3.0.1, the most approching one about that (that not only font that have the issue) was your work about that. Maybe it's not the origin of the issue but I will not have many time for that by now.

@Rmano: all needed infos and dependencies to install: https://redmine.darktable.org/projects/darktable/wiki/Building_darktable_26 (nothing has changed since 2.6 for compiling darktable, I'm always on these steps in Ubuntu 20.04 and compiling actual master).

**Comment by Rmano** [comment]
Hmmm. I do not think that was the culprit. I reverted that commit and the problem is still here. 
If I find how to bisect I'll try again...

**Comment by Rmano** [comment]
@Nilvus  ok, I reduced it a lot but I am stuck. My `git-bisect` arrived here: 

![image](https://user-images.githubusercontent.com/6414907/80239440-8b48ae00-8660-11ea-91b4-c65c89d8f0d9.png)

...but the problem now is that 18404309fa0356b4245a8d843bff6babefa2cf34 doen not compile, gives me an error:

```
[ 67%] Building C object src/iop/CMakeFiles/vibrance.dir/introspection_vibrance.c.o
/home/romano/software/darktable/darktable/build/src/iop/introspection_colorout.c: In function ‘introspection_init’:
/home/romano/software/darktable/darktable/build/src/iop/introspection_colorout.c:179:35: error: ‘DT_COLORSPACE_PQ_REC2020’ undeclared (first use in this function); did you mean ‘DT_COLORSPACE_LIN_REC2020’?
     { "DT_COLORSPACE_PQ_REC2020", DT_COLORSPACE_PQ_REC2020 },
                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                   DT_COLORSPACE_LIN_REC2020
```

Hmmm... let's see if I can exit from the hole here...

**Comment by Rmano** [comment]
Ok. So I did manage to jump over the bad commits (I think that's because something on rawspeed), and I have this:

```Bisecting: 0 revisions left to test after this (roughly 0 steps)
[18404309fa0356b4245a8d843bff6babefa2cf34] First CSS clean, just clean some unnecessary lines as they are already set elsewhere
```

Which I can't really see why should fail...

**Comment by Rmano** [comment]
This change:
```
diff --git a/data/themes/darktable.css b/data/themes/darktable.css
index 76bc21c56..47822d538 100644
--- a/data/themes/darktable.css
+++ b/data/themes/darktable.css
@@ -223,6 +223,7 @@ eventbox *,
 box,
 box *
 {
+  font-size: 1em;
   background-color: transparent;
 }
```
fixes the problem, but I am not sure at all if it's the right one.

**Comment by TurboGit** [comment]
> fixes the problem, but I am not sure at all if it's the right one.

Using px was definitely wrong.

**Comment by Rmano** [comment]
If I want to create a PR, against which branch do you want it?

**Comment by TurboGit** [comment]
Now fixed.
