### ISSUE TITLE
Failure to build with libavif 0.8.2

### ISSUE THREAD

**Issue by ArchangeGabriel** [darktable-org/darktable#6530]
They have been API+ABI changes in upstream libavif 0.8.2, and Darktable does not build against it:
```
/build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c:141:12: error: too many arguments to function ‘avifDecoderParse’
  141 |   result = avifDecoderParse(decoder, &raw);
      |            ^~~~~~~~~~~~~~~~
In file included from /build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c:22:
/usr/include/avif/avif.h:707:12: note: declared here
  707 | avifResult avifDecoderParse(avifDecoder * decoder);
      |            ^~~~~~~~~~~~~~~~
/build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c: In function ‘dt_imageio_avif_read_color_profile’:
/build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c:309:12: error: too many arguments to function ‘avifDecoderParse’
  309 |   result = avifDecoderParse(decoder, &raw);
      |            ^~~~~~~~~~~~~~~~
In file included from /build/darktable/src/darktable-3.2.1/src/common/imageio_avif.c:22:
/usr/include/avif/avif.h:707:12: note: declared here
  707 | avifResult avifDecoderParse(avifDecoder * decoder);
      |            ^~~~~~~~~~~~~~~~
```

**Comment by kmilos** [comment]
Works for me now after e531b66f486f31a7119b418ba0ecfee9cd49a79b

FYI, [updated libavif should appear soon for mingw-w64](https://github.com/msys2/MINGW-packages/pull/7165) as well ;)

**Comment by ArchangeGabriel** [comment]
Thanks indeed, should have been mentionned in PR https://github.com/darktable-org/darktable/pull/6594.
