### ISSUE TITLE
Does not build with gcc and g++ 9.2

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#2888]
Trying to build on Debian Unstable after the upgrade to gcc/g++ 9.2 fails. See error output from running: ./build.sh --prefix /opt/darktable --build-type Release

/home/mir/git/darktable/src/common/bilateral.c: In function ‘dt_bilateral_splat’:
/home/mir/git/darktable/src/common/bilateral.c:138:25: error: ‘in’ not specified in enclosing ‘parallel’
  138 |       const float L = in[index];
      |                         ^
/home/mir/git/darktable/src/common/bilateral.c:130:9: error: enclosing ‘parallel’
  130 | #pragma omp parallel for default(none) shared(b)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:154:75: error: ‘oy’ not specified in enclosing ‘parallel’
  154 |         const size_t ii = grid_index + ((k & 1) ? ox : 0) + ((k & 2) ? oy : 0) + ((k & 4) ? oz : 0);
      |                                                             ~~~~~~~~~~~~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:130:9: error: enclosing ‘parallel’
  130 | #pragma omp parallel for default(none) shared(b)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:154:96: error: ‘oz’ not specified in enclosing ‘parallel’
  154 |         const size_t ii = grid_index + ((k & 1) ? ox : 0) + ((k & 2) ? oy : 0) + ((k & 4) ? oz : 0);
      |                                                                                  ~~~~~~~~~~~~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:130:9: error: enclosing ‘parallel’
  130 | #pragma omp parallel for default(none) shared(b)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c: In function ‘blur_line’:
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: ‘size1’ not specified in enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/bilateral.c:215:30: error: ‘offset1’ not specified in enclosing ‘parallel’
  215 |     size_t index = (size_t)k * offset1;
      |                    ~~~~~~~~~~^~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:219:53: error: ‘offset3’ not specified in enclosing ‘parallel’
  219 |       buf[index] = buf[index] * w0 + w1 * buf[index + offset3] + w2 * buf[index + 2 * offset3];
      |                                               ~~~~~~^~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:224:32: error: ‘size3’ not specified in enclosing ‘parallel’
  224 |       for(int i = 2; i < size3 - 2; i++)
      |                          ~~~~~~^~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:238:24: error: ‘offset2’ not specified in enclosing ‘parallel’
  238 |       index += offset2 - offset3 * size3;
      |                ~~~~~~~~^~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:216:22: error: ‘size2’ not specified in enclosing ‘parallel’
  216 |     for(int j = 0; j < size2; j++)
      |                    ~~^~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:211:9: error: enclosing ‘parallel’
  211 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c: In function ‘blur_line_z’:
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: ‘size1’ not specified in enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/bilateral.c:177:30: error: ‘offset1’ not specified in enclosing ‘parallel’
  177 |     size_t index = (size_t)k * offset1;
      |                    ~~~~~~~~~~^~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:181:35: error: ‘offset3’ not specified in enclosing ‘parallel’
  181 |       buf[index] = w1 * buf[index + offset3] + w2 * buf[index + 2 * offset3];
      |                             ~~~~~~^~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:186:32: error: ‘size3’ not specified in enclosing ‘parallel’
  186 |       for(int i = 2; i < size3 - 2; i++)
      |                          ~~~~~~^~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:199:24: error: ‘offset2’ not specified in enclosing ‘parallel’
  199 |       index += offset2 - offset3 * size3;
      |                ~~~~~~~~^~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:178:22: error: ‘size2’ not specified in enclosing ‘parallel’
  178 |     for(int j = 0; j < size2; j++)
      |                    ~~^~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:173:9: error: enclosing ‘parallel’
  173 | #pragma omp parallel for default(none) shared(buf)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c: In function ‘dt_bilateral_slice’:
/home/mir/git/darktable/src/common/bilateral.c:265:23: error: ‘b’ not specified in enclosing ‘parallel’
  265 |   for(int j = 0; j < b->height; j++)
      |                       ^~
/home/mir/git/darktable/src/common/bilateral.c:263:9: error: enclosing ‘parallel’
  263 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:271:25: error: ‘in’ not specified in enclosing ‘parallel’
  271 |       const float L = in[index];
      |                         ^
/home/mir/git/darktable/src/common/bilateral.c:263:9: error: enclosing ‘parallel’
  263 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:284:48: error: ‘oy’ not specified in enclosing ‘parallel’
  284 |                                    + b->buf[gi + oy] * (1.0f - xf) * (yf) * (1.0f - zf)
      |                                             ~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:263:9: error: enclosing ‘parallel’
  263 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:286:48: error: ‘oz’ not specified in enclosing ‘parallel’
  286 |                                    + b->buf[gi + oz] * (1.0f - xf) * (1.0f - yf) * (zf)
      |                                             ~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:263:9: error: enclosing ‘parallel’
  263 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:282:33: error: ‘norm’ not specified in enclosing ‘parallel’
  282 |                          + norm * (b->buf[gi] * (1.0f - xf) * (1.0f - yf) * (1.0f - zf)
      |                            ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  283 |                                    + b->buf[gi + ox] * (xf) * (1.0f - yf) * (1.0f - zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  284 |                                    + b->buf[gi + oy] * (1.0f - xf) * (yf) * (1.0f - zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  285 |                                    + b->buf[gi + ox + oy] * (xf) * (yf) * (1.0f - zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  286 |                                    + b->buf[gi + oz] * (1.0f - xf) * (1.0f - yf) * (zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  287 |                                    + b->buf[gi + ox + oz] * (xf) * (1.0f - yf) * (zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  288 |                                    + b->buf[gi + oy + oz] * (1.0f - xf) * (yf) * (zf)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  289 |                                    + b->buf[gi + ox + oy + oz] * (xf) * (yf) * (zf));
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:263:9: error: enclosing ‘parallel’
  263 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c: In function ‘dt_bilateral_slice_to_output’:
/home/mir/git/darktable/src/common/bilateral.c:311:23: error: ‘b’ not specified in enclosing ‘parallel’
  311 |   for(int j = 0; j < b->height; j++)
      |                       ^~
/home/mir/git/darktable/src/common/bilateral.c:309:9: error: enclosing ‘parallel’
  309 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:317:25: error: ‘in’ not specified in enclosing ‘parallel’
  317 |       const float L = in[index];
      |                         ^
/home/mir/git/darktable/src/common/bilateral.c:309:9: error: enclosing ‘parallel’
  309 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:329:46: error: ‘oy’ not specified in enclosing ‘parallel’
  329 |                                  + b->buf[gi + oy] * (1.0f - xf) * (yf) * (1.0f - zf)
      |                                           ~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:309:9: error: enclosing ‘parallel’
  309 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:331:46: error: ‘oz’ not specified in enclosing ‘parallel’
  331 |                                  + b->buf[gi + oz] * (1.0f - xf) * (1.0f - yf) * (zf)
      |                                           ~~~^~~~
/home/mir/git/darktable/src/common/bilateral.c:309:9: error: enclosing ‘parallel’
  309 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
/home/mir/git/darktable/src/common/bilateral.c:327:31: error: ‘norm’ not specified in enclosing ‘parallel’
  327 |       const float Lout = norm * (b->buf[gi] * (1.0f - xf) * (1.0f - yf) * (1.0f - zf)
      |                          ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  328 |                                  + b->buf[gi + ox] * (xf) * (1.0f - yf) * (1.0f - zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  329 |                                  + b->buf[gi + oy] * (1.0f - xf) * (yf) * (1.0f - zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  330 |                                  + b->buf[gi + ox + oy] * (xf) * (yf) * (1.0f - zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  331 |                                  + b->buf[gi + oz] * (1.0f - xf) * (1.0f - yf) * (zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  332 |                                  + b->buf[gi + ox + oz] * (xf) * (1.0f - yf) * (zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  333 |                                  + b->buf[gi + oy + oz] * (1.0f - xf) * (yf) * (zf)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  334 |                                  + b->buf[gi + ox + oy + oz] * (xf) * (yf) * (zf));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/bilateral.c:309:9: error: enclosing ‘parallel’
  309 | #pragma omp parallel for default(none) shared(out)
      |         ^~~
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:116: src/CMakeFiles/lib_darktable.dir/common/bilateral.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/mir/git/darktable/src/common/color_picker.c: In function ‘color_picker_helper_4ch_parallel’:
/home/mir/git/darktable/src/common/color_picker.c:87:31: error: ‘mean’ not specified in enclosing ‘parallel’
   87 |     float *const tmean = mean + 3 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:88:31: error: ‘mmin’ not specified in enclosing ‘parallel’
   88 |     float *const tmmin = mmin + 3 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:89:31: error: ‘mmax’ not specified in enclosing ‘parallel’
   89 |     float *const tmmax = mmax + 3 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:94:23: error: ‘box’ not specified in enclosing ‘parallel’
   94 |     for(size_t j = box[1]; j < box[3]; j++)
      |                       ^
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:98:37: error: ‘width’ not specified in enclosing ‘parallel’
   98 |         const size_t k = 4 * (width * j + i);
      |                               ~~~~~~^~~
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:99:30: error: ‘pixel’ not specified in enclosing ‘parallel’
   99 |         const float L = pixel[k];
      |                              ^
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:102:23: error: ‘w’ not specified in enclosing ‘parallel’
  102 |         tmean[0] += w * L;
      |                     ~~^~~
/home/mir/git/darktable/src/common/color_picker.c:82:9: error: enclosing ‘parallel’
   82 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c: In function ‘color_picker_helper_bayer_parallel’:
/home/mir/git/darktable/src/common/color_picker.c:207:30: error: ‘msum’ not specified in enclosing ‘parallel’
  207 |     float *const tsum = msum + 4 * tnum;
      |                         ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:208:31: error: ‘mmin’ not specified in enclosing ‘parallel’
  208 |     float *const tmmin = mmin + 4 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:209:31: error: ‘mmax’ not specified in enclosing ‘parallel’
  209 |     float *const tmmax = mmax + 4 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:210:32: error: ‘cnt’ not specified in enclosing ‘parallel’
  210 |     uint32_t *const tcnt = cnt + 4 * tnum;
      |                            ~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:215:23: error: ‘box’ not specified in enclosing ‘parallel’
  215 |     for(size_t j = box[1]; j < box[3]; j++)
      |                       ^
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:219:23: error: ‘filters’ not specified in enclosing ‘parallel’
  219 |         const int c = FC(j + roi->y, i + roi->x, filters);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:219:45: error: ‘roi’ not specified in enclosing ‘parallel’
  219 |         const int c = FC(j + roi->y, i + roi->x, filters);
      |                                             ^~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:220:32: error: ‘width’ not specified in enclosing ‘parallel’
  220 |         const size_t k = width * j + i;
      |                          ~~~~~~^~~
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:222:30: error: ‘pixel’ not specified in enclosing ‘parallel’
  222 |         const float v = pixel[k];
      |                              ^
/home/mir/git/darktable/src/common/color_picker.c:202:9: error: enclosing ‘parallel’
  202 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c: In function ‘color_picker_helper_xtrans_parallel’:
/home/mir/git/darktable/src/common/color_picker.c:334:30: error: ‘msum’ not specified in enclosing ‘parallel’
  334 |     float *const tsum = msum + 3 * tnum;
      |                         ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:335:31: error: ‘mmin’ not specified in enclosing ‘parallel’
  335 |     float *const tmmin = mmin + 3 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:336:31: error: ‘mmax’ not specified in enclosing ‘parallel’
  336 |     float *const tmmax = mmax + 3 * tnum;
      |                          ~~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:337:32: error: ‘cnt’ not specified in enclosing ‘parallel’
  337 |     uint32_t *const tcnt = cnt + 3 * tnum;
      |                            ~~~~^~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:342:23: error: ‘box’ not specified in enclosing ‘parallel’
  342 |     for(size_t j = box[1]; j < box[3]; j++)
      |                       ^
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:346:23: error: ‘xtrans’ not specified in enclosing ‘parallel’
  346 |         const int c = FCxtrans(j, i, roi, xtrans);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:346:23: error: ‘roi’ not specified in enclosing ‘parallel’
  346 |         const int c = FCxtrans(j, i, roi, xtrans);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:347:32: error: ‘width’ not specified in enclosing ‘parallel’
  347 |         const size_t k = width * j + i;
      |                          ~~~~~~^~~
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
/home/mir/git/darktable/src/common/color_picker.c:349:30: error: ‘pixel’ not specified in enclosing ‘parallel’
  349 |         const float v = pixel[k];
      |                              ^
/home/mir/git/darktable/src/common/color_picker.c:329:9: error: enclosing ‘parallel’
  329 | #pragma omp parallel default(none)
      |         ^~~
[ 30%] Linking CXX executable darktable-rs-identify
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:181: src/CMakeFiles/lib_darktable.dir/common/color_picker.c.o] Error 1
/home/mir/git/darktable/src/common/dwt.c: In function ‘dwt_subtract_layer’:
/home/mir/git/darktable/src/common/dwt.c:261:9: error: ‘size’ not specified in enclosing ‘parallel’
  261 | #pragma omp parallel for default(none) shared(bl, bh) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c:261:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/dwt.c: In function ‘dwt_subtract_layer_sse’:
/home/mir/git/darktable/src/common/dwt.c:236:9: error: ‘size’ not specified in enclosing ‘parallel’
  236 | #pragma omp parallel for default(none) shared(bl, bh) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c:236:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/dwt.c:241:5: error: ‘v4_lpass_mult’ not specified in enclosing ‘parallel’
  241 |     _mm_store_ps(&(bl[i]), _mm_mul_ps(_mm_load_ps(&(bl[i])), v4_lpass_mult));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/dwt.c:236:9: error: enclosing ‘parallel’
  236 | #pragma omp parallel for default(none) shared(bl, bh) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c: In function ‘dwt_add_layer’:
/home/mir/git/darktable/src/common/dwt.c:219:9: error: ‘i_size’ not specified in enclosing ‘parallel’
  219 | #pragma omp parallel for default(none) shared(layers) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c:219:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/dwt.c:221:51: error: ‘img’ not specified in enclosing ‘parallel’
  221 |   for(int i = 0; i < i_size; i++) layers[i] += img[i];
      |                                                   ^
/home/mir/git/darktable/src/common/dwt.c:219:9: error: enclosing ‘parallel’
  219 | #pragma omp parallel for default(none) shared(layers) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c: In function ‘dwt_add_layer_sse’:
/home/mir/git/darktable/src/common/dwt.c:197:9: error: ‘i_size’ not specified in enclosing ‘parallel’
  197 | #pragma omp parallel for default(none) shared(layers) schedule(static)
      |         ^~~
/home/mir/git/darktable/src/common/dwt.c:197:9: error: enclosing ‘parallel’
/home/mir/git/darktable/src/common/dwt.c:201:5: error: ‘img’ not specified in enclosing ‘parallel’
  201 |     _mm_store_ps(&(layers[i]), _mm_add_ps(_mm_load_ps(&(layers[i])), _mm_load_ps(&(img[i]))));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mir/git/darktable/src/common/dwt.c:197:9: error: enclosing ‘parallel’
  197 | #pragma omp parallel for default(none) shared(layers) schedule(static)
      |         ^~~
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:324: src/CMakeFiles/lib_darktable.dir/common/dwt.c.o] Error 1
[ 30%] Built target darktable-rs-identify
make[1]: *** [CMakeFiles/Makefile2:954: src/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by mir07** [comment]
For other builders out there. To be able to build with GCC/G++ 9.x as default you must remove your build folder and rebuild using the following command:
export CXX=g++-8; export CC=gcc-8; ./build.sh --prefix /opt/darktable --build-type Release

**Comment by LebedevRI** [comment]
The last comment makes it sound like this can be closed?

**Comment by LebedevRI** [comment]
You didn't specify the version, master builds fine with gcc9

**Comment by mir07** [comment]
> You didn't specify the version, master builds fine with gcc9
Sorry. It is 2.6.x.

**Comment by Nilvus** [comment]
If it is darktable 2.6.x, the best is probably to use the compiled debian package version (from debian unstable or from third party repositories mentioned on darktable.org website). There probably won't be any new minor 2.6 version as the next major 3.0 release (actual master) will have its features freeze in a month and then the developers will correct most of bugs known as possible.

That's said, I suppose to close this issue and use debian existing packages or compile the master version.

**Comment by bremner** [comment]
Note that the existing darktable packages will be removed from Debian testing within approximately 1 month due to this build failure. I understand the OBS version has it's own patch. The OBS patch is a bit large and complicated to just copy to Debian.

**Comment by johnny-bit** [comment]
darktable now builds fine with gcc and CI matrix enforces that build must pass :)
