### ISSUE TITLE
Git master : Compile error : error: ‘_get_cache_filename’ defined but not used [-Werror=unused-function]

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#18794]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When I compile git master I get this compilation error:
```c
In file included from /home/magnus/test/darktable-test/darktable/build/lib/darktable/plugins/introspection_lut3d.c:50:
/home/magnus/test/darktable-test/darktable/src/iop/lut3d.c:452:13: error: ‘_get_cache_filename’ defined but not used [-Werror=unused-function]
  452 | static void _get_cache_filename(const char *const lutname, char *const cache_filename)
      |             ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [lib/darktable/plugins/CMakeFiles/lut3d.dir/build.make:82: lib/darktable/plugins/CMakeFiles/lut3d.dir/introspection_lut3d.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6548: lib/darktable/plugins/CMakeFiles/lut3d.dir/all] Error 2
``` 

### Steps to reproduce

1. Checkout git master. Cd darktable.
2. cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/test/darktable-test/install -DCMAKE_BUILD_TYPE=Release ..
3. make -j32
```c
In file included from /home/magnus/test/darktable-test/darktable/build/lib/darktable/plugins/introspection_lut3d.c:50:
/home/magnus/test/darktable-test/darktable/src/iop/lut3d.c:452:13: error: ‘_get_cache_filename’ defined but not used [-Werror=unused-function]
  452 | static void _get_cache_filename(const char *const lutname, char *const cache_filename)
      |             ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[2]: *** [lib/darktable/plugins/CMakeFiles/lut3d.dir/build.make:82: lib/darktable/plugins/CMakeFiles/lut3d.dir/introspection_lut3d.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6548: lib/darktable/plugins/CMakeFiles/lut3d.dir/all] Error 2
``` 

### Expected behavior

Sucessful build

### Logfile | Screenshot | Screencast

Git bisect result:
```bash
200c4b9bc80776b42f69ac6fa2fcca1ae1faa308 is the first bad commit
commit 200c4b9bc80776b42f69ac6fa2fcca1ae1faa308
Author: Hanno Schwalm <hanno@schwalm-bremen.de>
Date:   Sat May 10 10:54:40 2025 +0200

    Lut3D static maintenance
    
    Internal functions should be static and have a leading underscore,
    take care about c++ code.

 src/iop/lut3d.c       | 149 +++++++++++++++++++++++++++-----------------------
 src/iop/lut3dgmic.cpp |   8 +--
 2 files changed, 84 insertions(+), 73 deletions(-)
```

### Commit

200c4b9bc80776b42f69ac6fa2fcca1ae1faa308

### Where did you obtain darktable from?

Self compiled.

### darktable version

11f26a81c48bd3f38f65a4b6819b3aaf02ee6f71

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable 12.10 Bookworm

### Describe your system

Debian stable 12.10 Bookworm
gcc version 12.2.0 (Debian 12.2.0-14)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

No relevent here.

**Comment by KarlMagnusLarsson** [comment]
If I comment out  `-Wall` from  `darktable/cmake/compiler-warnings.cmake`, then I can compile again:
```
#  CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wall)
```

**Comment by jenshannoschwalm** [comment]
already fixed in a41f307

**Comment by KarlMagnusLarsson** [comment]
> already fixed in [a41f307](https://github.com/darktable-org/darktable/commit/a41f3075225db806875c555f3c1857b75831477e)
Yes, it works for me. Thank you.
