### ISSUE TITLE
Can't build on Ubuntu 22.04 after #17961

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#17977]
### Describe the bug

```
/home/bill/src/darktable/darktable/src/control/control.c:329:28: error: implicit declaration of function ‘g_atomic_int_exchange’; did you mean ‘g_atomic_int_and’? [-Werror=implicit-function-declaration]
  329 |   const gboolean cleanup = g_atomic_int_exchange(&s->running, DT_CONTROL_STATE_DISABLED) == DT_CONTROL_STATE_CLEANUP;
      |                            ^~~~~~~~~~~~~~~~~~~~~
      |                            g_atomic_int_and

```

### Steps to reproduce

1. downloadf current master on Ubuntu 22.04
2. try and compile

### Expected behavior

should compile

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

current master 12/9

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

glilb is version 2.72 and #17961 requires 2.74

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
This also breaks the appimage build.
