### PR TITLE
refactor: dedupe code iterating over container's children

### PR DESCRIPTION
**Pull request by ralfbrown**
Created several utility functions, and then replaced various loops by calls to the new utility functions.

### CODE REVIEW

File: src/dtgtk/utility.h [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+GtkWidget *dtgtk_container_nth_child(GtkContainer *container, int which);
+
+// remove all of the children we've added to the container.  Any which no longer have any references will
+// be destroyed.
+void dtgtk_container_remove_children(GtkContainer *container);
+
+// delete all of the children we've added to the container.  Use this function only if you are SURE
+// there are no other references to any of the children (if in doubt, use dtgtk_container_remove_children
+// instead; it's a bit slower but safer).
+void dtgtk_container_destroy_children(GtkContainer *container);
```
Comment (dterrahe) [inline src/dtgtk/utility.h:39]: Hm. Theoretically this is correct, but the cases where we want to empty a container but there still is somewhere a ref out there that is still useful afterwards are going to be really limited and they would require special handling anyway and not benefit from either of these utility functions (or explicitly remove/reparent the one widget they want to keep before destroying the rest).

My gut feeling would be that if someone is emptying a container but isn't sure if they'll leave dangling refs, I'd _want_ them to cause a crash and solve the problem rather than create an unusual situation that nobody has dealt with (and a likely memory leak). Too much "better be safe than sorry" code already that nobody understands what special situations they are trying to deal with and that gets copy pasted everywhere.

But OK, that's just MHO first thing in the morning. Feel free to disagree and ignore!

Comment (ralfbrown) [reply src/dtgtk/utility.h:39]: We just had to fix a crash for precisely that reason, where a gtk_container_remove got "optimized" into a gtk_widget_destroy....

Comment (dterrahe) [reply src/dtgtk/utility.h:39]: Ah, I thought that crash was caused by the issue we discussed before, calling widget_destroy with two arguments instead of one. But Lua is keeping refs around. Seems unlikely to me that those would still be useful after they are removed from the container, but I'm not going to dive into that whole subsystem just to figure that out.

@wpferguson without having any idea what I'm talking about (so just dismiss me if this won't work for _whatever_ reason) if lua keeps refs to widgets it puts into a container (i.e. doesn't transfer ownership) would it be possible to do what the docs for `gtk_widget_destroy` suggests, i.e.
_"you should connect to the “destroy” signal if you hold a reference to widget and you wish to remove it when this function is called."_ and then notify (without causing a crash) anyone who still wants to access the widget from lua afterwards that it already has been destroyed and might not contain anything useful anymore. But maybe the previous crashes were caused by lua itself double freeing a destroyed widget during cleanup rather than user code trying to access it?

@ralfbrown if lua _can't_ clean up after a destroy, it may be worth adding that to the comment in `dtgtk_container_destroy_children` as something to look out for.

Comment (wpferguson) [reply src/dtgtk/utility.h:39]: Did the crash have anything to do with resetting the exporter?

Each lua widget has a callback running somewhere, so destroying the widget without removing the callback could have problems.

Comment (wpferguson) [reply src/dtgtk/utility.h:39]: Can someone point me to the original issue so that I can get up to speed please?

**Comment by dterrahe** [comment]
#8418 was caused by changing "removing widgets from a container" to "destroying the widgets", which _also_ removes them from the container, but causes problems for anybody else who holds a ref. It was resolved by reverting that change, but I was wondering what would happen with this ref to a now presumably useless (because invisible) widget.

When you say a lua widget has a callback running, do you mean _from_ the gtk widget to the lua code (that callback would disappear if the widget gets destroyed) or a callback within the lua code? If the latter, the pointer it holds would have to be NULLed by the _destroy_ signal from gtk (alternatively you can use `g_set_weak_pointer `to do this) and any access to it should check for a NULL. I have no idea how this would fit into the lua model, so your answer may well be that this is infeasible. In which case the C code will just continue to have to be careful never to destroy anything that might still be reffed by lua.

**Comment by wpferguson** [comment]
I'm going to build the crashing version and play with it to see why lua is having a problem with it.  Lua does have it's own widget garbage collector, so it very well could be a double free.

**Comment by TurboGit** [comment]
@wpferguson : this is the commit I've done to fix the crash: 8e9e3c3eda033da6068540242b60636d3b7b7bdc

**Comment by TurboGit** [comment]
I'm wondering if we are not hitting a ref-count issue.

**Comment by wpferguson** [comment]
Anyone tried compiling a build-type Debug lately?  I keep getting

```
In file included from /home/bill/src/darktable/darktable/src/iop/channelmixerrgb.c:30:0,
                 from /home/bill/src/darktable/darktable/build/lib/darktable/plugins/introspection_channelmixerrgb.c:164:
/home/bill/src/darktable/darktable/src/common/illuminants.h: In function ‘CCT_reverse_lookup’:
/home/bill/src/darktable/darktable/src/common/illuminants.h:564:32: error: initializer element is not constant
   static const float T_range = T_max - T_min;
                                ^~~~~
compilation terminated due to -Wfatal-errors.
[ 73%] Building C object lib/darktable/plugins/CMakeFiles/rotatepixels.dir/introspection_rotatepixels.c.o
lib/darktable/plugins/CMakeFiles/channelmixerrgb.dir/build.make:68: recipe for target 'lib/darktable/plugins/CMakeFiles/channelmixerrgb.dir/introspection_channelmixerrgb.c.o' failed
make[2]: *** [lib/darktable/plugins/CMakeFiles/channelmixerrgb.dir/introspection_channelmixerrgb.c.o] Error 1
CMakeFiles/Makefile2:6320: recipe for target 'lib/darktable/plugins/CMakeFiles/channelmixerrgb.dir/all' failed
make[1]: *** [lib/darktable/plugins/CMakeFiles/channelmixerrgb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

T_max and T_min are declared static const float right above this


In the meantime `fprintf(stderr...` is my friend :smiley:

**Comment by ralfbrown** [comment]
No problem doing a debug build with GCC 8.4 on master as of just now.  Then again, the compilers have been getting pickier with every version (I remember when GCC 2.x(IIRC) would happily accept . and -> interchangeably regardless of whether the variable was an object or a pointer).

**Comment by wpferguson** [comment]
I'm still on Ubuntu 18.04 with GCC 7.5.0, which is probably the issue...

If I understand the code correctly this
`gtk_container_foreach(GTK_CONTAINER(d->storage_extra_container), _destroy_child, NULL);
`
destroys all of the storage widgets.  Then this
```
  for(const GList *it = darktable.imageio->plugins_storage; it; it = g_list_next(it))
  {
    dt_imageio_module_storage_t *module = (dt_imageio_module_storage_t *)it->data;
    fprintf(stderr, "adding %s\n", module->name(module));
    dt_bauhaus_combobox_add(d->storage, module->name(module));
    if(module->widget)
    {
      fprintf(stderr, "added the widget\n");
      gtk_container_add(GTK_CONTAINER(d->storage_extra_container), module->widget);
    }
  }
```
adds them back.  If I add print statements to see what's happening and I start darktable with no lua storages enabled it starts fine.  Then, when I enable a lua storage this happens:

```
in _on_storage_list_changed
removing all storage widgets
adding Edit with GIMP
added the widget
adding LaTeX book template
added the widget
adding file on disk
added the widget
adding piwigo
added the widget
adding send as email
adding website gallery
added the widget
setting combobox
combox set

Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.

```

It looks like all of the storage widgets get destroyed, but there isn't a lua widget yet so it's not a lua widget causing the crash.  Then the lua widget gets added along with the rest of previous widgets.  The function returns and the display refreshes and there's a crash.  I don't think the widgets exist after they've been destroyed, so adding the address that they used to live at is just a segfault waiting to happen.  I think if we could just raise the storage_changed signal this would happen anyway.

**Comment by ralfbrown** [comment]
Yup, reading pointers out of deallocated storage is bad news....
For this particular bit of code, `module->widget` is the additional reference to the widget that would need to be invalidated by the signal handler.  But it's easier and much more efficient to simply re-use the existing widgets than to recreate them all, hence `gtk_container_remove` is a better choice here.

**Comment by wpferguson** [comment]
@dterrahe not a problem.  I was sitting at work bored, so instead I got to have fun bug chasing :smile:

**Comment by dterrahe** [comment]
Sorry to bring this up rather late, but what is the logic of putting these utility functions under the dtgtk directory/namespace?

I find it quite hard myself to understand the logic in the directory structure, but I sort of had concluded that dtgtk was a set of dt specific (variants of gtk) widgets.

gui/gtk.h&.c contain helper functions for the dt ui layout. But also some more generic gtk helpers. Seems like the new set fits into that latter category? So maybe it could be added to this file, or this file could be split (in dt_ui and gtk_utility or something like that) Not feeling strongly about it; if you are happy with the location you picked then I don't mind. But if you had doubts/would have liked guidance...

**Comment by ralfbrown** [comment]
I don't have strong feelings about the location either.  dtgtk/ seemed like the obvious place since I was basically wrapping gtk functionality.

**Comment by TurboGit** [comment]
For me `src/dtgtk` are new widgets whereas src/gui' are more for high level dialogs. But then in `src/gui` we have `gtk.h`, `gtkentry.h` and `accelerators.h` ! So at this stage it is hard to see some sensible choices :)

**Comment by ralfbrown** [comment]
Whatever you decide, I'll move the files and fix the includes as needed.

**Comment by TurboGit** [comment]
After more thinking I suppose a sensible choice would be to move all routines in dtghk/utility.h into gui/gtk.h and prefix them with `dt_iu_` instead of `dtgtk_`.

@dterrahe : How does that sound to you ?

**Comment by dterrahe** [comment]
I think gui/gtk.c-h is a good location.

But now that I've looked at it more closely, I get the impression that there are two groups of functions in there:
- dt_gui: generic helper functions/wrappers around gtk.
- dt_ui: I get the impression that these are more specifically dealing with the dt layout (dt_ui_t; two side panels, middle area, top/bottom etc)

Ignore the functions that I introduced (dt_ui_label_new, dt_ui_scroll_wrap, dt_ui_notebook_page) because I knew not what I was doing. Maybe these should all be rename to dt_gui if the above distinction is correct (or maybe it doesn't matter enough? But then maybe we could still, at the bottom, document the general distinction and that these are exceptions. Makes it easier next time).

So to conclude, I'm thinking maybe the new functions should be named dt_gui_...

Could be wrong of course and seeing a pattern that wasn't intentional. Then dt_ui/dt_gui would both be fine.

**Comment by ralfbrown** [comment]
Is the concensus to 

- move the contents of dtgtk/utility.h into gui/gtk.h
- rename the new functions dt_gui_*
- move dtgtk/utility.c to gui/utility.c

**Comment by dterrahe** [comment]
> * move dtgtk/utility.c to gui/utility.c

move the contents of dtgtk/utility.c into gui/gtk.c

At least, that's what _I_ meant 😉 @TurboGit?

**Comment by TurboGit** [comment]
> move the contents of dtgtk/utility.c into gui/gtk.c

Yes, that's what I meant. Sorry for the typo.

**Comment by TurboGit** [comment]
@ralfbrown : you can go ahead, thanks.

**Comment by ralfbrown** [comment]
Rebased and renamed/moved.

**Review by TurboGit — APPROVED** [review]
Works for me, testing seems ok. I merge this now to be sure we get some field testing before the next release.
