### ISSUE TITLE
4.0.1 fails to build tests; missing include in src/common/variables.h

### ISSUE THREAD

**Issue by podiki** [darktable-org/darktable#12604]
**Describe the bug/issue**
Darktable 4.0.1 fails to build on GNU Guix with the following error:

```
In file included from /tmp/guix-build-darktable-4.0.1.drv-0/darktable-4.0.1/src/tests/variables.c:2:
/tmp/guix-build-darktable-4.0.1.drv-0/darktable-4.0.1/src/common/variables.h:60:76: error: unknown type name 'dt_image_basic_exif_t'
void dt_variables_set_exif_basic_info(dt_variables_params_t *params, const dt_image_basic_exif_t *basic_exif);
```

Full logs available if needed. This is with the same package definition and everything else used to build Darktable 4.0.0.

The change looks to be introduced in 22da554cf3a724e1e74e5ca950ee1e7d76e0e608 as a fix for #11209. The reference to `dt_image_basic_exif_t` comes from `src/common/image.h`. I'm not sure why this wasn't reported before or since the 4.0.1 release, my guess is that other builds/distros do not enable or try tests which Guix uses `-DBUILD_TESTING=ON`. Without this configure flag the build succeeds (but then tests cannot be run, which is the default on Guix and is only disabled if absolutely necessary). I'm surprised this wasn't caught by any CI build systems or a pre-release check for building/running tests.

I can confirm that adding the include
```
#include "common/image.h"
```
to variables.h fixes the build.

**To Reproduce**
One can build with GNU Guix as a package manager or distro, using a package definition updating source to 4.0.1 or with the package transformation as
```
guix build darktable --with-source=darktable=https://github.com/darktable-org/darktable/releases/download/release-4.0.1/darktable-4.0.1.tar.xz
```
to see the build error.

**Which commit introduced the error**
22da554cf3a724e1e74e5ca950ee1e7d76e0e608 and the change to variables.h

**Platform**

* darktable version : 4.0.1 (release version)
* OS                : Linux 5.19.11
* Linux - Distro    : GNU Guix
* Memory            : 16G
* Graphics card     : AMD 6700 XT
* Graphics driver   : Mesa 21.3.8
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 21.1.4
* Desktop           : StumpWM
* GTK+              : yes
* gcc               : built with clang (tried, 11, 12, 13, 14; default is 11)
* cflags            : 
* CMAKE_BUILD_TYPE  : (not specified)

**Comment by Nilvus** [comment]
@podiki: would be better if you propose a pull request for that. Should be easy for you if you find that. Would be faster. On my side, with another compiler, I never had that issue (and I compile few times per week darktable master).

**Comment by podiki** [comment]
@Nilvus Yes I could make a PR. But can you confirm that when you build with `-DBUILD_TESTING=ON` for 4.0.1 you do not get this failure? Been a while since I've done any C, but seems like a straightforward issue with a missing include, but I don't know all the clang/cmake options involved here.

**Comment by Nilvus** [comment]
I never use that function. I just say that I didn't reproduce when using default compile options.

**Comment by podiki** [comment]
Okay (I guess by "default compile options" you mean not specifying anything at all?). In any event, I hope there is a CI or regular developers building and running the tests, exactly for this reason.

I can make a PR later this week, though feel free anyone with commit access to make the tiny change before that.

**Comment by TurboGit** [comment]
Done, closing.
