### ISSUE TITLE
Lumix LX7 black point wrong

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#10008]
**To Reproduce**

1. Import raw and sidecar from https://tech.kovacs-telekes.org/files/2021-09-15-darktable-lx7-blackpoint/
2. Select step 12 in history (this loads the black point values from darktable 3.6, all = 143)
3. Reset the _raw black/white point_ module (this will set the current values, all = 128
4. See colour cast

**Expected behavior**
Proper black levels are used

**Screenshots**
![Screenshot_20210915_202706](https://user-images.githubusercontent.com/3177739/133489977-91dc68e5-df17-441a-bf3e-5ece03d94216.png)

**Which commit introduced the error**
Probably dae697b @LebedevRI 

In rawspeed the black value seems to be 150 (neither 128, not 143 that I saw in darktable 3.6), and these lines have not been updated for 7 years:
https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml#L6008-L6032

Wrong value seems to come from EXIF:
```
kofa@eagle:~/darktable$ exiftool `locate *P1060660.RW2`|grep -i black
Black Level Red                 : 128
Black Level Green               : 128
Black Level Blue                : 128
```

**Platform**

* darktable version : 3.7.0+1050~g0c01bab23
* OS : Linux - kernel 5.11.0-31
* Linux - Distro : Ubuntu 21.04
* Memory : 64 GB
* Graphics card : NVidia 1060/6GB
* Graphics driver : 460.91.03-0ubuntu0.21.04.1
* OpenCL installed : yes
* OpenCL activated : yes
* Xorg : 1:7.7+22ubuntu1
* Desktop : KDE 5.80.0-0ubuntu1
* GTK+ : 3.24.25-1ubuntu4.1
* gcc : 10.3.0
* cflags : none
* CMAKE_BUILD_TYPE : RelWithDebInfo

**Comment by kofa73** [comment]
Maybe this is caused by commit dae697b1 ?
>     * Fix black point reading for Panasonic cameras
>      Fixes https://github.com/darktable-org/darktable/issues/9811

The exif contains a black value of 128, which is wrong for my camera:
```
kofa@eagle:~/darktable$ exiftool `locate *P1060660.RW2`|grep -i black
Black Level Red                 : 128
Black Level Green               : 128
Black Level Blue                : 128
```

**Comment by kofa73** [comment]
So, I guess this will take some time to get into darktable (the revert commit is on the rawspeed 'develop' branch; if I switch my version to that one, and try to build darktable master, I get:
```
/home/kofa/darktable/src/common/imageio_rawspeed.cc: In function ‘dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t*, const char*, dt_mipmap_buffer_t*)’:
/home/kofa/darktable/src/common/imageio_rawspeed.cc:234:28: error: ‘TYPE_FLOAT32’ was not declared in this scope; did you mean ‘TYPE_FLOAT’?
  234 |     if(r->getDataType() == TYPE_FLOAT32)
      |                            ^~~~~~~~~~~~
      |                            TYPE_FLOAT
```
What would be the best solution for the time being?

**Comment by LebedevRI** [comment]
I would guess you'd want to simply locally revert darktable's dae697b.

**Comment by kofa73** [comment]
I ended up locally undoing https://github.com/darktable-org/rawspeed/pull/292 (just those few lines calculating the black levels).

**Comment by Nilvus** [comment]
Just for info, we had users reported that issues on Lumix too (other models) in darktable french forum. And I can reproduce too with my Panasonic G9. I created a preset with correct values to avoid that issue.

**Comment by jdneumeyer77** [comment]
I reviewed quite a few samples off raw pixels. I think if the raw format is version 4 or less then the black levels need the magically number 15 added to them; otherwise, read the black level as-is. I didn't notice this when testing my fix since I didn't raise the exposure much and very quickly looked a few samples. Some are dependent on the scene.

I didn't try all of them, but confirmed a bunch from this list. These are v4 and affected.
```
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G100 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G110 - 3 2.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G90 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G91 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G9 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-G95 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-GH5 - 4 3.RW2
Panasonic Raw Version           : 0380
Raw Format                      : 4
Panasonic - DC-GH5M2 - 4 3.RW2
Panasonic Raw Version           : 0500
Raw Format                      : 6
Panasonic - DC-GH5S - 3 2.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 5
Panasonic - DC-GX7MK3 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-GX850 - 4 3.RW2
Panasonic Raw Version           : 0360
Raw Format                      : 4
Panasonic - DC-GX880 - 3 2.RW2
Panasonic Raw Version           : 0360
Raw Format                      : 4
Panasonic - DC-GX9 - 3 2.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
Panasonic - DC-GX9 - 4 3.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 4
```

I only found one v5? Any one know of others? The GH5S was not affected and reading the black levels works.
```
Panasonic - DC-GH5S - 3 2.RW2
Panasonic Raw Version           : 0390
Raw Format                      : 5
```

And my camera the S5 is raw format 6 along with the S1, S1H, and S1R. And they have the correct black levels with my fix.

I think only 15 should be added if raw format is less then or equal to 4. What do you think @LebedevRI?

**Comment by LebedevRI** [comment]
Sounds plausible, but i didn't check.
There's another bug - if there is a black level override in cameras.xml,
why are we overriding it with values from EXIF?

**Comment by jdneumeyer77** [comment]
I'm not sure. I do know my camera tends to have varied values between 509 and 513. So if they're right and dynamic why not read them. Otherwise we could have an override for the cameras where the black level isn't right. But I don't understand where the magic number 15 came from either.

**Comment by kofa73** [comment]
I'm not sure setting the value indicated in the cameras.xml file (150 in case of the LX7) would be a good idea.
With ISO 80 shots, darktable gives the following automatic values:

* 142, 142, 142, 142
* 143, 143, 143, 143
* 142, 143, 143, 142
* 142, 143, 142, 142
* 141, 142, 141, 141

I stopped checking, but it seems that the '+15 magic' is needed for this camera.

**Comment by jdneumeyer77** [comment]
Just submitted a PR for my proposed fix.

https://github.com/darktable-org/rawspeed/pull/307

**Comment by jsmucr** [comment]
> Just for info, we had users reported that issues on Lumix too (other models) in darktable french forum. And I can reproduce too with my Panasonic G9. I created a preset with correct values to avoid that issue.

GX80/GX85/GX7MKII is affected too.

**Comment by Nilvus** [comment]
I close this issue as this is now fixed in darktable master with update of rawspeed submodule for so all Panasonic RAW.
