### ISSUE TITLE
darktable doesn't build on openSUSE with LTO

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#7386]
**Describe the bug**
```
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libdarktable.so.QEG3wD.ltrans43.ltrans.o: in function `icuLikeCompare':
[  453s] /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:189: undefined reference to `u_foldCase_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:190: undefined reference to `u_foldCase_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libdarktable.so.QEG3wD.ltrans43.ltrans.o: in function `icuRegexpFunc':
[  453s] /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:67: undefined reference to `u_errorName_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:67: undefined reference to `u_errorName_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:67: undefined reference to `u_errorName_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libdarktable.so.QEG3wD.ltrans43.ltrans.o: in function `icuCaseFunc16':
[  453s] /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:400: undefined reference to `u_strToUpper_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:67: undefined reference to `u_errorName_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:402: undefined reference to `u_strToLower_67'
[  453s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/libdarktable.so.QEG3wD.ltrans43.ltrans.o: in function `icuLoadCollation':
[  453s] /home/abuild/rpmbuild/BUILD/darktable-3.5.0~git102.7a6e50775/src/common/sqliteicu.c:67: undefined reference to `u_errorName_67'
[  453s] collect2: error: ld returned 1 exit status
```

```
$ pkg-config --libs icu-i18n
-licui18n -licuuc -licudata
```

Looking at the linker line I only see /usr/lib64/libicui18n.so but not the other libs ...

Full log:
https://build.opensuse.org/package/live_build_log/graphics:darktable:master/darktable/openSUSE_Tumbleweed/x86_64

This is caused by #7253

**Comment by cryptomilk** [comment]
@phweyland :-)

**Comment by cryptomilk** [comment]
```
nm -D /usr/lib64/libicuuc.so | grep u_foldCase
00000000000f7e70 T u_foldCase_67
```

**Comment by phweyland** [comment]
> You need to link against a few more libs ...

I thought they come all together. I'll add  icu-uc & icu-data.
Thank you for the hint.
