### ISSUE TITLE
Preset's not selectable on MacOS Ventura

### ISSUE THREAD

**Issue by borgmanJeremy** [darktable-org/darktable#12708]
**Describe the bug/issue**
After upgrading my M1 Air to MacOS Ventura yesterday, I am no longer able to select presets from any menu. 

**To Reproduce**
1. Open any image in Darktable view
2. Under any module click the preset menu and try to click a preset
3. See that the menu options are not selectable

**Screencast**

https://user-images.githubusercontent.com/46930769/197823986-b644fa01-100b-4fa8-a862-7a79ce12c7ef.mov

**Which commit introduced the error**
Running on the latest release. Happy to build from source on the main branch or do a bisect if this will help. Seems to be more related to Ventura breaking something rather than Darktable breaking something. 

**Platform**
```
~ brew info darktable
==> darktable: 4.0.1.1
https://www.darktable.org/
/opt/homebrew/Caskroom/darktable/4.0.1.1 (123B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/darktable.rb
```
* OS                :MacOS Ventura 13.0
* Hardware      :M1 Air
* Display          : Issue occurs on laptop screen and external display

**Additional context**
I have tried removing the cache folder and the issue is still present. I also have tried uninstalling and reinstalling darktable. 

If I use the keyboard I can get the menu items to highlight, but pressing space or enter does not make them apply. 

Credit for the image used in the screencast:  https://commons.wikimedia.org/wiki/File:Hummingbird.jpg

**Comment by borgmanJeremy** [comment]
I reinstalled Ventura from scratch and the issue is still there.

**Comment by MStraeten** [comment]
reproducible - even with new current master build using macports 2.8 & Xcode 14.0.1
next step: need to upgrade macports for ventura, after installing xcode 14.1 ...

**Comment by Snowchess** [comment]
Macbook Air M2, Ventura:
Moving the Mouse over an Option and click does not work,
but when you stop the mouse pointer one second there until the describing text shows up it works.

**Comment by parafin** [comment]
Is it reproducible with both ARM and Intel builds?

**Comment by borgmanJeremy** [comment]
Unfortunately I only have an ARM device and I cannot get ventura running in an x86 VM yet.

**Comment by parafin** [comment]
That's another question. I wasn't asking about on which hardware, but which build. There are 2 macOS builds of the latest release:
https://github.com/darktable-org/darktable/releases/tag/release-4.0.1
https://www.darktable.org/install/

**Comment by borgmanJeremy** [comment]
I installed via brew and if I inspect the binary it looks to be the arm64 build:
```
darktable.app/Contents/MacOS 
> file darktable
darktable: Mach-O 64-bit executable arm64
```

**Comment by parafin** [comment]
So please try x86_64 build (download DMG, open it and run darktable from there, no need to install anything).

**Comment by borgmanJeremy** [comment]
@MStraeten Are you able to test that? I actually wiped my laptop and rolled back to Monterey.

**Comment by MStraeten** [comment]
its reproducible also with my x86_64 build. After updating my macports I'll check if a build with sdk13 helps ...

**Comment by MStraeten** [comment]
macports updated to ventura.
the issue is reproducible with build using sdk12.3 and official build.
build fails with sdk13.0 from commandline tools 14.1 RC2:

```
In file included from /Users/martinstraeten/src/darktable/src/osx/osx.mm:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:62:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Headers/PrintCore.h:26:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Headers/PDEPluginInterface.h:22:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/ppd.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/cups.h:27:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/ipp.h:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/cups/http.h:39:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/netinet/ip.h:86:2: fatal error: unknown type name 'u_int'
        u_int   ip_hl:4,                /* header length */
        ^
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_heif.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_libraw.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/imageio_j2k.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/pwstorage/backend_libsecret.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/sqliteicu.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/common/cups_print.c.o
[ 53%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printing.c.o
[ 53%] Building C object bin/CMakeFiles/lib_darktable.dir/common/printprof.c.o
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/osx/osx.mm.o] Error 1
```

so i will file a new issue on osx build with sdk13

**Comment by MStraeten** [comment]
found a solution for that build issue, so was able to build with sdk13.0.
issue keeps being reproducible - so no quick solution for that :(

**Comment by MStraeten** [comment]
found a workaround:

- open preset menu
- hover mouse over outside the menu over a module header or module parameter 
- wait until the tooltip occurs
- then hover mouse back to the menu
- then the highlighting of menuitems on mouseover is active, and selecting by click works fine

So it seems the menu doesn't get focus properly

**Comment by MaxKorlaar** [comment]
You can also use your keyboard to navigate through the menu items, although it doesn't always seem to work for me.

**Comment by pradyut-c** [comment]
Same issue in mac m1 after Ventura update

**Comment by iradraconis** [comment]
Same here.

**Comment by michmill1970** [comment]
Agreed.  Reproducible on both my Intel i9 and my Apple M1 with Ventura.

**Comment by TiredOfGuessing** [comment]
I too spent some time with this issue just today (dt 4.0.1 M1 w Ventura). I just found out it has already been reported a the gtk site, so think that absolves dt code?
   **widgets not reacting to mouse hover/click on macOS Ventura**
   [https://gitlab.gnome.org/GNOME/gtk/-/issues/5305](url)

Although not assigned yet, I assume this will be fixed in gtk (3.x/4.x) at some point and dt can use the patched gtk version without major issues?

**Comment by maxwxyz** [comment]
Is there any news? I'm on Ventura Intel and this workaround does not work. I am not able to use any menu items which pop up like this (every right click menu, presets, styles, on some dialogs the cursor gets weird and I cannot click on any button or test input field). It is practically not usable on Ventura.

> found a workaround:
> 
>     * open preset menu
> 
>     * hover mouse over outside the menu over a module header or module parameter
> 
>     * wait until the tooltip occurs
> 
>     * then hover mouse back to the menu
> 
>     * then the highlighting of menuitems on mouseover is active, and selecting by click works fine
> 
> 
> So it seems the menu doesn't get focus properly

**Comment by MStraeten** [comment]
Not here this issue is closed since it’s tracked with the issue mentioned above

**Comment by thommym** [comment]
For the record it seems as this was solved with the 4.2.1 patch update that was out 2023-02-21. At least I've no problems on MacOS 13 And M1 Max any longer.
