### ISSUE TITLE
opencl no longer working in 3.5, previously it was

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#8963]
**Describe the bug/issue**
_darktable-cltest_ is giving me an error on the latest build of v3.5 on Ubuntu 20.04.

My live darktable v3.4.1 was working fine and so was _darktable-cltest._  This was run via /usr/bin/

For a while I've been compiling v3.5 into my /opt folder.  Today when I run _darktable-cltest_ from /opt/darktable/bin it works fine.  This is version 3.5.0+2159~g22aba1f90-dirty.

Earlier this week I overwrote my live installation with the version via http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_20.04/.  This is currently version 3.5.0~git2210.85569c3aa2-1

Open CL isn't working in darktable and when I run _darktable-cltest_ via /usr/bin it errors with :

_0.118279 [opencl_init] compiling program `extended.cl' ..
0.118372 [opencl_fopen_stat] could not open file `/home/phil/.cache/darktable/cached_kernels_for_GeForceGTX670_4607301/extended.cl.bin'!
0.118384 [opencl_load_program] could not load cached binary program, trying to compile source
0.118404 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/extended.cl' MD5: 'd76c789b5bf363755c03729f853eb7fe'
0.156267 [opencl_build_program] could not build program: -11
0.156294 [opencl_build_program] BUILD STATUS: -2
0.156305 BUILD LOG:
0.156314 In file included from <kernel>:20:
/usr/share/darktable/kernels/colorspace.h:427:12: error: subscripted access is not allowed for OpenCL vectors RGB.x -= D65[0];
           ^   ~
/usr/share/darktable/kernels/colorspace.h:428:12: error: subscripted access is not allowed for OpenCL vectors RGB.y -= D65[1];
           ^   ~
/usr/share/darktable/kernels/colorspace.h:442:39: error: subscripted access is not allowed for OpenCL vectors RGB.x = Ych.y * native_cos(Ych.z) + D65[0];
                                      ^   ~
/usr/share/darktable/kernels/colorspace.h:443:39: error: subscripted access is not allowed for OpenCL vectors RGB.y = Ych.y * native_sin(Ych.z) + D65[1];
                                      ^   ~
0.156339 [opencl_init] failed to compile program `extended.cl'!
0.156356 [opencl_init] no suitable devices found.
0.156360 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.156365 [opencl_init] initial status of opencl enabled flag is OFF._

I've deleted the _.cache/darktable_ folder and still get the same error, I've also reinstalled darktable via OBS and still get the same error.

**To Reproduce**
Run _darktable-cltest_

**Expected behavior**
I expect _darktable-cltest_ to run successfully.

**Which commit introduced the error**
The error above mentioned D65 and so does a recent commit 85569c3 "colorbalancergb: use constant D65 for Ych/Yrg", possibly just a coincidence.

**Comment by johnny-bit** [comment]
@aurelienpierre - this is the error @jenshannoschwalm mentioned in comment to 85569c3aa2e4d35c7b0826ba7abf442c6bb5d75c :)

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by phil20099** [comment]
I confirm this is now working, thank you.
