### PR TITLE
Imageio PFM fixes

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
1. Allocate temp buffer only for what we need
2. Check for correct size of read data from file and possibly report as corrupted
3. some constify and simplifications

### CODE REVIEW

**Comment by wpferguson** [comment]
Wont compile on Ubuntu 22.04, gcc 12.3.

```
/home/bill/src/darktable/darktable/src/imageio/imageio_pfm.c: In function ‘dt_imageio_open_pfm’:
/home/bill/src/darktable/darktable/src/imageio/imageio_pfm.c:129:7: error: not enough perfectly nested loops before ‘const’
  129 |       const size_t target_row = made_by_photoshop ? row : img->height - 1 - row;
      |       ^~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2070: bin/CMakeFiles/lib_darktable.dir/imageio/imageio_pfm.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2540: bin/CMakeFiles/lib_darktable.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

**Comment by wpferguson** [comment]
Commenting out `DT_OMP_FOR(collapse(2))` (both instances) works.  Thanks @ralfbrown for the suggestion.

**Comment by ralfbrown** [comment]
You don't need to comment them out completely (that removes the multi-threading), just change them to a simple `DT_OMP_FOR()`.  Under ideal comditions, the `collapse` is a little more efficient, but it should make minimal difference on images large enough to have a perceptible load time.

**Comment by wpferguson** [comment]
That works.  Do you want to do a PR or do you want me to, or should we leave it for @jenshannoschwalm ?
