### ISSUE TITLE
Cannot compile Darktable on Fedora 30 beta (GCC9 / OpenMP 4.0)

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#2458]
**Describe the bug**

Darktable from master, as well as the latest stable release (2.6.2).

**To Reproduce**

1. Use Fedora 30 with GCC9
2. Try to compile; get an OpenMP compile error
3. Attempt to compile again without OpenMP (`--disable-openmp`); get a compiler error

I've tried compiling on another machine I've also upgraded to the Fedora 30 beta, and also compiling 2.6.2 as well — and was met with the same results with those other attemps.

**Expected behavior**

Darktable compilation was working fine in Fedora 29. Only after upgrading to 30 (currently frozen in beta) did Darktable stop compiling properly.

**Platform:**

 - Darktable Versions: master branch & 2.6.2
 - OS: Fedora 30 beta
 - CPU: Intel Core i7-7500U
 - GPU: Intel HD Graphics 620 (rev 02)

**Additional context**

Fedora 30 switched to GCC9 & OpenMP 4.0 — and this changes things a bit:
https://gcc.gnu.org/gcc-9/porting_to.html

Rawspeed recently updated to support GCC9 / OMP4 (and compiles fine on F30):
https://github.com/darktable-org/rawspeed/commit/c82d0f30a8f8865592013f0156c5e745ae41c250

**Example of compile errors**

Standard recommend compile with `./build.sh --prefix /usr/local --build-type Release`:
```
[ 26%] Building C object src/CMakeFiles/lib_darktable.dir/common/cache.c.o
/home/garrett/Source/darktable/src/common/bilateral.c: In function ‘dt_bilateral_splat’:
/home/garrett/Source/darktable/src/common/bilateral.c:138:25: error: ‘in’ not specified in enclosing ‘parallel’
  138 |       const float L = in[index];
      |                         ^
/home/garrett/Source/darktable/src/common/bilateral.c:130:9: error: enclosing ‘parallel’
  130 | #pragma omp parallel for default(none) shared(b)
      |         ^~~
/home/garrett/Source/darktable/src/common/bilateral.c:154:75: error: ‘oy’ not specified in enclosing ‘parallel’
  154 |         const size_t ii = grid_index + ((k & 1) ? ox : 0) + ((k & 2) ? oy : 0) + ((k & 4) ? oz : 0);
      |                                                             ~~~~~~~~~~~~~~^~~~
/home/garrett/Source/darktable/src/common/bilateral.c:130:9: error: enclosing ‘parallel’
[...]
```
(and there are many more OpenMP-related errors, but I don't want to flood this bug report)

Here's what happens with `./build.sh --prefix /usr/local --build-type Release --disable-openmp`:

```
[...]
In file included from /home/garrett/Source/darktable/src/common/color_picker.c:20:
In function ‘dt_unreachable_codepath_with_caller’,
    inlined from ‘dt_color_picker_helper’ at /home/garrett/Source/darktable/src/common/color_picker.c:407:5:
/home/garrett/Source/darktable/src/common/darktable.h:549:3: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  549 |   fprintf(stderr, "[dt_unreachable_codepath] {%s} %s:%d (%s) - we should not be here. please report this to "
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  550 |                   "the developers.",
      |                   ~~~~~~~~~~~~~~~~~~
  551 |           description, file, line, function);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[...]
```

---

I'm happy to try anything you suggest, including compiling from any branches to test out.

Thanks in advance!

**Comment by aurelienpierre** [comment]
I will take a look at that once Fedora 30 stable is released.

**Comment by garrett** [comment]
@aurelienpierre:  Fedora 30 has just been released! It's so fresh, the website has been updated, but the official release notes haven't been posted yet. (Oops.)

Meanwhile, I've reinstalled and downgraded to Fedora 29 on my personal laptop for the time being, specifically to be able to compile Darktable. As my work laptop is still Fedora 30, I can test compilation of Darktable — on both Fedora 29 and 30, if needed.

---

BTW: Thanks for all your work on Darktable! Everything you've done is amazing, and why I'm currently being risky, running Darktable from git (and have db backups of course). It's beautiful, produces even better results (with filmic, color balance, better presets with LUT, etc.), and is much faster on my XPS13 (which only has an Intel GPU). The next big release will be amazing (just like last release, but even more so).

**Comment by berndf** [comment]
Gentoo also has gcc9 now and the corresponding bug report: https://bugs.gentoo.org/685042
I started to add fixes (http://jakascorner.com/blog/2016/06/omp-data-sharing-attributes.html is quite clear in how attributes should be handled - gcc9 just seems to be stricter than gcc8 in enforcing this).
Could you have a look at 
https://github.com/berndf/darktable/commit/14717dd7d8906c822cd35c1834340b62ec123798 ?
Here I fixed the first 3 source files.
I wonder whether there is a more elegant solution, but default(shared) should better be avoided, so that it's necessary to do this somewhat tedious work...

**Comment by garrett** [comment]
@berndf: Thanks for working on this!

---

Here's what I get with `./build.sh --prefix /usr/local --build-type Release` when trying to compile on my Fedora 30 machine today using your `gcc9` branch:

```
[ 25%] Building C object src/CMakeFiles/lib_darktable.dir/common/colorspaces.c.o
/home/garrett/Source/darktable/src/common/color_picker.c: In function ‘color_picker_helper_4ch_parallel’:
/home/garrett/Source/darktable/src/common/color_picker.c:104:19: error: ‘cst_to’ not specified in enclosing ‘parallel’
  104 |         if(cst_to == iop_cs_LCh)
      |            ~~~~~~~^~~~~~~~~~~~~
/home/garrett/Source/darktable/src/common/color_picker.c:86:9: error: enclosing ‘parallel’
   86 | #pragma omp parallel default(none) shared(mean,mmin,mmax,width,box,pixel,w)
      |         ^~~
gmake[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:181: src/CMakeFiles/lib_darktable.dir/common/color_picker.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1482: src/CMakeFiles/lib_darktable.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```

**Comment by jenshannoschwalm** [comment]
Hi i see the pull requests ... but in the meantime

just to let you know, at least when using the dt2.6.2 release archive
compiling with:
clang 8 and libomp 4.5
works fine after allowing it in  CMakeLists.txt by find_llvm("8;7;6.0;5.0;4.0;3.9")

No problem detected and good performance.

**Comment by brothermechanic** [comment]
Same issue
I try https://github.com/cryptomilk/darktable/tree/cmake-omp but no susses (
[build.zip](https://github.com/darktable-org/darktable/files/3227455/build.zip)

Please help

**Comment by jenshannoschwalm** [comment]
Well, i used the "official" darktable-2.6.2.tar.xz release source. Extract and create a build directory inside the dt source tree.

The idea is; clang8 & clang8++ both are *not* so strict with omp pragmas as gcc9 is.
So install the clang toolchain plus it's omp library plus devel package (on fedora this is clang, clang-tools-extra, libomp and libomp-devel) all version 8.0

When configuring you will have to make sure the compilation does *not* use gcc but clang - your logfile shows using gcc!
An easy way to do so is using the cmake-gui, make sure you are using clang as you c-compiler.
Also remember to change CMakeLists.txt Line 345 to find_llvm("8;7;6.0;5.0;4.0;3.9")

Run the configure test and watch for unmet sources, the generate the makefile (Buttons "Configure" & "Generate".
The configue log should show:
...
Found LLVM 8.0.0
Found clang compiler - /usr/bin/clang-8
Found clang opencl-c.h header in /usr/lib64/clang/8.0.0/include

...
Looking for OpenMP
Found OpenMP_C: -fopenmp=libomp (Required is at least version "4.0") 
Found OpenMP_CXX: -fopenmp=libomp (Required is at least version "4.0") 
Found OpenMP: TRUE (Required is at least version "4.0")  
Looking for OpenMP - found (system)



cd to build and do make; later sudo make install

**Comment by brothermechanic** [comment]
Show me your flags please
This is my
CC="clang"                            
CXX="clang++"                         
CFLAGS="${CFLAGS} -flto"              
CXXFLAGS="${CXXFLAGS} -flto"          
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
Build log
http://dpaste.com/2H00YVA

**Comment by jenshannoschwalm** [comment]
I don't know about the gentoo build chain but your clang++ at least is not working ...

Your logfile show in lines 385++

-- The CXX compiler identification is Clang 8.0.0
-- The C compiler identification is Clang 8.0.0
-- Check for working CXX compiler: /usr/lib/llvm/8/bin/clang++
-- Check for working CXX compiler: /usr/lib/llvm/8/bin/clang++ -- broken

Also you use the non-release sources.

**Comment by elsandosgrande** [comment]
Pardon me if it is in bad taste to reply to a nearly-full-month-old closed issue, but, using GCC 8.3.0-r1, which is the latest available in Gentoo stable (ACCEPT_KEYWORDS="amd64"), as opposed to 9.1.0-r1 in Gentoo testing (ACCEPT_KEYWORDS="~amd64"), even with the [GentooLTO](https://github.com/InBetweenNames/gentooLTO) overlay present and enabled, results in a successful compilation and installation of Darktable. 

@brothermechanic It seems to me, at least from a glossary overview, that link-time optimization does not really work with Clang, at least without specifying the linker with `-fuse-ld=linker`, replacing linker with bfd, gold, or llvm, whichever you prefer (I am personally partial to `-fuse-ld=bfd`), which is why the verification presented above failed. 
By the way, there are three pieces of advice I would like to mention: 
1. While it is true that critical packages, such as Mesa, do strip presented flags to avoid breakages, only leaving some intact, like `-march` for example, I would advise against using unsafe and aggressive compiler flags by default, at least without plenty of spare time on your hands.
2. If you are so inclined, like me, or simply require even one additional processor cycle saved, then I suggest that you refer to the overlay linked above for a safer method of enabling the unstable and aggressive optimization flags present in GCC.
3. And lastly, I suggest that you have the latest version of GCC available in Gentoo stable as well as the latest available in Gentoo testing, as this is one example of why it is crucial to have a fallback, Blender being another example.

Once again, pardon me if it is in bad taste to reply to such an old issue and for veering off of the original topic by some degree and I hope that this reply is helpful to others in the future, at least in the more recent future.

Have a nice day everybody!

**Comment by parafin** [comment]
I guess this is fixed and should be closed.

**Comment by TurboGit** [comment]
Closing indeed!
