### ISSUE TITLE
Unable to build latest master (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#11762]
**Describe the bug/issue**
Latest master fails to build

```
[ 68%] Linking C shared module libclahe.so
In file included from /home/jade/.local/git/darktable/build/lib/darktable/plugins/introspection_colorbalancergb.c:211:
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c: In function 'commit_params':
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c:1268:12: error: 'd' not specified in enclosing 'parallel'
           d->gamut_LUT[index] = UV_star_prime[0] * UV_star_prime[0] + UV_star_prime[1] * UV_star_prime[1];
            ^~
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/build.make:69: lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/introspection_colorbalancergb.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5008: lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I'm assuming, based on the *not specified in enclosing 'parallel'* part, that this is the same kind of error that I ran into before in #11717. If it is it is a known issue related to the, not yet deprecated, GCC version that is being used. @TurboGit was able to fix this previously.

**To Reproduce**
1. Clone or Pull repo,
2. Configure,
3. Build using GCC 8.x.y

**Expected behavior**
Able to build without errors/failure

**Which commit introduced the error**

```
$ git bisect bad
b430651608db365e61050e861b3178afbf6dcca6 is the first bad commit
commit b430651608db365e61050e861b3178afbf6dcca6
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Wed May 4 23:05:39 2022 +0200

    colorbalancergb: introduce darktable UCS 22

:040000 040000 14747f2fb8c5e90204e3a9197230807ee1b588b6 800fa71db0ae621b9c867ceecbe33b60f8658ed4 M      src
```

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.12)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : **gcc 8.3.0**
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 1.0.0.9
* Sqlite        : 3.27.2
* Optimization  : none

**Comment by jade-nl** [comment]
@aurelienpierre just changed something ([rename a variable to avoid shadowing](https://github.com/darktable-org/darktable/commit/7ca04fddf50522138fdfe7bdb5aee0178505da27) and/or [colorbalancergb: try t
o fix compiler error (false positive ?)](https://github.com/darktable-org/darktable/commit/eab250744f98e80a85a430d2263e0bdc2f4b87dc) and it is possible again to build darktable on my side of things.

Closing this one for now.

**Comment by ralfbrown** [comment]
GCC 7 and 8 behave differently from newer versions and clang when it comes to declaring const variables "shared" in OpenMP directives.  That's why we have the dt_omp_sharedconst macro.
