### PR TITLE
Monochrome images need one blackpoint correction in rawprepare, performance gains

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
Keep old edits for monochromes by avaraging blackpoint corrections before updating the sliders.

The 3 upper black level correction sliders are invisible for true monochromes

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
Again i don't know why CI fails to build completely.

**Comment by johnny-bit** [comment]
@jenshannoschwalm - The CI problem is in no part your fault.

it's this code:

```
/home/runner/work/darktable/darktable/src/src/common/utility.c:705:42: error: implicit declaration of function ‘localeconv’ [-Werror=implicit-function-declaration]
  705 |   const struct lconv *currentLocalConv = localeconv ();
      |                                          ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

This is caused by  #9088 IMHO and so @rslsp1 or @TurboGit - can you take a look? probably it's just a missing include.

**Comment by TurboGit** [comment]
> This is caused by #9088 IMHO and so @rslsp1 or @TurboGit - can you take a look? probably it's just a missing include.

Should be fixed now!

**Comment by jenshannoschwalm** [comment]
3.6 or 3.8?

**Comment by TurboGit** [comment]
@jenshannoschwalm : the answer to your question at this stage is simple, if bug fix it is for 3.6, if a new feature it is for 3.8.

**Comment by jenshannoschwalm** [comment]
Certainly new feature, was just wandering as there was no planned-version tag.

**Comment by johnny-bit** [comment]
I hope I tagged it appropriately :)

**Comment by johnny-bit** [comment]
Well... we're on 3.8 cycle now so this can be IMO now reviewed & tested...

@jenshannoschwalm - leica monochrome dngs are cool for testing this?

**Comment by jenshannoschwalm** [comment]
>  leica monochrome dngs are cool for testing this?

exactly :-)

**Review by TurboGit — APPROVED** [review]
See nothing wrong and tested on a Leica Monochrome image without issue. Good to go. Thanks.
