### PR TITLE
fix osx compilation error caused by #6013

### PR DESCRIPTION
**Pull request by johnny-bit**
This should fix the osx compilation issue from #6013 raised by @MStraeten :)

### CODE REVIEW

**Comment by MStraeten** [comment]
Build was successful. Thanks

**Review by TurboGit — APPROVED** [review]
Thanks !
