### PR TITLE
Async printers

### PR DESCRIPTION
**Pull request by TurboGit**
Please read carefully as this is not an area I know well.  Thanks.

### CODE REVIEW

File: src/common/cups_print.h [hunk 1]
```diff
@@ -59,15 +59,12 @@ typedef struct dt_print_info_t
   dt_paper_info_t paper;
 } dt_print_info_t;
 
-// is some printers are available
-gboolean is_printer_available(void);
+// Asynchronous printer discovery, cb will be called for each printer found
```
Comment (pedrocr) [inline src/common/cups_print.h]: Is this really true? Won't we still block on cupsGetDests until all printers are discovered? Ideally we'd have some form of async way of getting printers from cups itself so that one slow printer doesn't block the discovery of all others. If I'm reading the diff correctly we won't get a single printer until all printers are discovered. That's still much better than before, at least we don't freeze the whole app.

Comment (pedrocr) [inline src/common/cups_print.h]: Looking at the cups API what we probably need is cupsEnumDests: 

https://www.cups.org/documentation.php/doc-2.0/api-cups.html#cupsEnumDests

That works with a callback so should allow us to add printers as they become available. I also wonder if we need to launch that job every time we open the print module in case printers have shown up or disappeared. Long gone are the times when the printer config was static.

Comment (TurboGit) [inline src/common/cups_print.h]: No, this is true since now this is done on a dt background job. cupsEnumDests() won't help as it returns only when all dest have been found. there is no support in cups for asynchronous printer discovery.

Comment (pedrocr) [inline src/common/cups_print.h]: That's not how I read your code and the cups api docs. Both cupsEnumDests and cupsGetDests only return when they have fully enumerated the printers. So your current code won't block the app (because it's run in a background job) but it won't show up any printers until all printers are enumerated. What cupsEnumDests does differently than cupsGetDests is that it will call a callback every time a printer is enumerated, so while it will only still return after all are enumerated it will call a callback of your choice on every printer while it's doing it. If you make that callback add a new printer you'll have available printers right away even though cupsEnumDests has not finished yet.

Either this solution or some other one exists because the gnome printer dialog is capable of listing printers and stay responsive even before being able to show all printer options. Our best bet is to find a way to generate a test case, probably by creating a network printer that doesn't exist so that cups tries to connect to it until timeout.

Comment (TurboGit) [inline src/common/cups_print.h]: I see what you mean now. I agree that cupsEnumDests is probably a better choice here.

**Comment by TurboGit** [comment]
Just pushed a new version which should be really asynchronous.

File: src/common/cups_print.c [hunk 2]
```diff
@@ -101,39 +107,50 @@ dt_printer_info_t *dt_get_printer_info(const char *printer_name)
...
-GList *dt_get_printers(void)
+static int _cancel = 0;
+
+static int _detect_printers_callback(dt_job_t *job)
 {
-  cups_dest_t *dests;
-  int num_dests = cupsGetDests(&dests);
-  int k;
-  GList *result = NULL;
+  dt_prtctl_t *pctl = dt_control_job_get_params(job);
```
Comment (houz) [inline src/common/cups_print.c]: You have to gfree() pctl.

File: src/common/cups_print.c [hunk 3]
```diff
@@ -101,39 +107,50 @@ dt_printer_info_t *dt_get_printer_info(const char *printer_name)
...
-  const int num_dests = cupsGetDests(&dests);
-  cupsFreeDests(num_dests, dests);
-  return (gboolean) num_dests > 0;
+  const dt_prtctl_t *pctl = (dt_prtctl_t *)user_data;
+  const char *psvalue = cupsGetOption("printer-state", dest->num_options, dest->options);
+
+  // check that the printer is ready
+  if (psvalue!=NULL && strtol(psvalue, NULL, 10) < IPP_PRINTER_STOPPED)
+  {
+    dt_printer_info_t *pr = dt_get_printer_info(dest->name);
```
Comment (LebedevRI) [inline src/common/cups_print.c]: I think pr should be `free()`d after being passed into `pctl->cb()`

**Comment by TurboGit** [comment]
New version pushed with fixes for both reported memory leak.

**Comment by LebedevRI** [comment]
Tested with cups-pdf, printing from DT seems to be [still] working fine.
One thing missing IMO - the only indication that i did press "print" button is the output of -d perf, there is no visual confirmation like with normal export.

**Comment by TurboGit** [comment]
The visual feedback was missing before, so a separate issue. I'll open a redmine ticket for this.

**Comment by TurboGit** [comment]
Ok to merge at this point?

**Comment by LebedevRI** [comment]
At this point *i* can not find anything anything obviously wrong here.
So i guess, looks good to me.

**Comment by TurboGit** [comment]
Thanks Roman. Merged.

**Comment by upegelow** [comment]
I'm having issues to build with openSUSE 13.2. The version of cups is 1.5.4.

/home/pegelow/darktable/src/common/cups_print.c: In function ‘_detect_printers_callback’:
/home/pegelow/darktable/src/common/cups_print.c:133:3: error: implicit declaration of function ‘cupsEnumDests’ [-Werror=implicit-function-declaration]
   const int res = cupsEnumDests(CUPS_MEDIA_FLAGS_DEFAULT, 30000, &_cancel, 0, 0, _dest_cb, pctl);
   ^
/home/pegelow/darktable/src/common/cups_print.c:133:33: error: ‘CUPS_MEDIA_FLAGS_DEFAULT’ undeclared (first use in this function)
   const int res = cupsEnumDests(CUPS_MEDIA_FLAGS_DEFAULT, 30000, &_cancel, 0, 0, _dest_cb, pctl);
                                 ^
/home/pegelow/darktable/src/common/cups_print.c:133:33: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors

**Comment by TurboGit** [comment]
cupsEnumDest() was added in 1.6, current CUPS version is 1.7. Your version is quite old, can you upgrade?

**Comment by upegelow** [comment]
cups 1.5.4 is the most recent one offered in openSUSE 13.2 which in turn is the current version of that distro. No option to upgrade, so I would be out :(

**Comment by LebedevRI** [comment]
Do not know if upgrading is the solution we want to enforce here, but in any case it really should not cause a build-failure.
*If* it is, then CMake should disable printing if version is too old; *if* it is not, such code should `#if`'ed, like in dt_get_papers()
Just my opinion.

**Comment by McBofh** [comment]
The latest version of cups available for Solaris 11.x is 1.4.5, so I agree with Roman's suggestion about CMake disabling printing if a suitable version is not found.

Requiring DT users to upgrade their installation of a system-delivered package like cups rests on the assumption that (a) there is a newer packaged version available for them, (b) that they have admin rights to install it, as well as (c) that they can roll their own if there is no package. Not user-friendly.

**Comment by TurboGit** [comment]
I did not force the upgrade, I was asking!

Ok, so if no upgrade possible I'll see if a too old CUPS version present we can fold back to standard (non async) code.

**Comment by TurboGit** [comment]
Compilation issue with old CUPS should now be fixed.
