### ISSUE TITLE
Unable to build latest master/development version (bisected)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#7944]
**Describe the bug**
I'm not able to build the latest development version.

Error at 62% It stops at  64%:

```
In file included from /home/jade/.local/git/darktable/build/lib/darktable/plugins/introspection_colorbalancergb.c:180:
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c: In function 'process':
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c:310:1: error: OpenMP constructs other than '#pragma omp ordered simd' may not be nested inside 'simd' region
     for_four_channels(c) Ych[c] = fmaxf(pix_in[c], 0.0f);
 ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/build.make:69: lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/introspection_colorbalancergb.c.o] Error 1
```

**To Reproduce**
1. Pull/clone latest version
2. start build process
3. it quits

**Expected behavior**
Builds cleanly

**Bisect info**
```

[stasis] jade ~/.local/git/darktable $ git bisect good
ca9f1a02e47abbbbb055b109b8365c257fe50337 is the first bad commit
commit ca9f1a02e47abbbbb055b109b8365c257fe50337
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Wed Jan 20 12:33:35 2021 +0100

    optimize the loops and make saturation more stable

:040000 040000 6bf1bd1a035a963d262fb5f491ebd75d1e94413e 0bc82e86e265bd0b6991680fc0933d56a7d2718b M      src
```

**Platform**
* darktable        : not able to build
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.7)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

[dt.script.2021.01.20.2023.log](https://github.com/darktable-org/darktable/files/5844826/dt.script.2021.01.20.2023.log)

Ping @aurelienpierre

**Comment by aurelienpierre** [comment]
-_____-

Fucking GCC. Works on GCC 9, 10 and probably 11, works on Clang (for once…), won't work on GCC 7 and 8. Fucking fucking GCC. Really.

**Comment by todd-prior** [comment]
I'm not at home where I complile but I can build it on Windows successfully but it won't run. Just comes up with a white dialog adn closes. I tried to get it to trigger something with debug but I can't see that it is generating any log files. I have tried even to run from a clean alternated configdir so that the databases are not in play...still not joy. I will try a bit harder tonight to see if the issue is me or something wider. What is the best way to get a log with useful information under these conditions

**Comment by johnny-bit** [comment]
Well... CI did yell about the build problem :P

**Comment by wgoetz** [comment]
> -_____-
> 
> Fucking GCC. Works on GCC 9, 10 and probably 11, works on Clang (for once…), won't work on GCC 7 and 8. Fucking fucking GCC. Really.


Hi Aurelien, pls add '9' to the nogo-list!
gcc version 9.3.0 (Gentoo 9.3.0-r2 p4)
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by johnny-bit** [comment]
Checking with CI builds it seems like @TurboGit might've fixed this in 42bfc77

**Comment by wgoetz** [comment]
Fixed both Ubuntu and gentoo builds, thx!
42bfc7767 (HEAD -> master, origin/master, origin/HEAD) colorbalancergb 2nd attempt: fix CI builded, no embedded simd directive.

**Comment by todd-prior** [comment]
> Well... CI did yell about the build problem :P
> 
> @todd-prior - start in terminal using `-d all` param, then paste log into txt file and attach as an attachment.

Thanks I will try tonight when I get home....

**Comment by johnny-bit** [comment]
@todd-prior - just make a new issue ;)

Aaand I'm closing this one since Pascal fixed it in 42bfc77 :)

**Comment by todd-prior** [comment]
Nice work….
